### ISSUE TITLE
Some missing features

### ISSUE THREAD

**Issue by psychobunny** [NodeBB/nodebb-theme-persona#1]
> Voting, direct reply and quoting.

Heh, how did I miss that. Brain too frazzled to think of a good design for voting right now, suggestions welcome

**Comment by frissdiegurke** [comment]
* group-labels

**Comment by psychobunny** [comment]
https://github.com/NodeBB/nodebb-theme-persona/issues/7

already closed, but maybe community hasn't been updated yet

**Comment by frissdiegurke** [comment]
seems to be up now, maybe it was just because of the move into user-settings that I missed it...

**Comment by psychobunny** [comment]
![](http://i.imgur.com/2VYM5Wy.png)

it should be in the topic view as well now, unless you're talking about something else

**Comment by frissdiegurke** [comment]
yes, that's what I wanted to say :smile: great work :wink:

**Comment by julianlam** [comment]
I assumed "Reply" and "Quote" would be inside the triple-dot menu, so I suppose if all else fails, it could go there.

I did like the "display-on-hover" thing we had going with Lavender, but it didn't work so well on phones.

**Comment by frissdiegurke** [comment]
In my opinion the relevant ("want to know") time-information within /recent and /unread is the time of the latest post within the topic, not of the topic itself. You've re-added that time with the link to the latest post within desktop-view (or I've been blind before). But within mobile view I'm missing that information.

**Comment by julianlam** [comment]
:+1:

**Comment by psychobunny** [comment]
haha before this thread escalates, I'm closing this having fixed the original items:

> Voting, direct reply and quoting

added back. Open new issues :P
