### ISSUE TITLE
Chat modal messed up

### ISSUE THREAD

**Issue by mrgame64** [NodeBB/nodebb-theme-persona#106]
The problem wasn't present in v1.0.21, and appeared after the update to v1.0.26.
The avatars in the chat are always at their full original size and the modal isn't correctly positioned.

After attempting to fix the images with CSS, I discovered that the chat doesn't scroll, and resizes to fit all the messages, even if it means going beyond the visible screen area.

<img width="1437" alt="screen shot 2015-08-01 at 16 11 15" src="https://cloud.githubusercontent.com/assets/5879873/9022115/fa255eb4-3867-11e5-95e4-a3581946e125.png"> <br>
<img width="1440" alt="screen shot 2015-08-01 at 16 14 44" src="https://cloud.githubusercontent.com/assets/5879873/9022126/74af47d0-3868-11e5-9b24-3c0f47ac4a6b.png">

**Comment by julianlam** [comment]
Please report your NodeBB commit hash.

**Comment by mrgame64** [comment]
I didn't push a commit, by the CSS fix I merely mean adding "width: 32px" to the chat-user-image in the Chrome inspector

**Comment by mrgame64** [comment]
I just found the source of the problem:
In order for the chat to look normally, the ul containing the should have a "chat-content" __*class*__, but it doesn't: instead it has the "chat-content" __*tag ID*__

**Comment by mrgame64** [comment]
Okay, my modification would've fixed it, but now the behaviour changed: now all the chat messages are loaded inside the h4 of the modal-header, which I believe isn't due to my intervention; I'm seeing the same behaviour upon reinstalling the theme.

Reverting to v1.0.21 seems to be the only working fix

<img width="1437" alt="screen shot 2015-08-01 at 22 08 39" src="https://cloud.githubusercontent.com/assets/5879873/9023400/ea32d478-3899-11e5-9ef6-e088d20303fe.png">

**Comment by mrgame64** [comment]
It turned out that the theme appears to be incompatible with NodeBB 0.7.2, but the needed fixes have been already implemented here: NodeBB/NodeBB@2593f1b

Seems that all I can do is clone the repo without specifying the version or wait for a 0.7.3 release

**Comment by julianlam** [comment]
Yeah, definitely you're not supposed to have upgraded to this theme version. I'll unpublish the too-new versions of Persona.

**Comment by julianlam** [comment]
If you'd like, you can clone the `master` branch, otherwise, you can run `npm install nodebb-theme-persona@1.0.21` to get the proper version for v0.7.2.
