### ISSUE TITLE
Not enough room in header for the search box (dbsearch plugin)

### ISSUE THREAD

**Issue by henrywright** [NodeBB/nodebb-theme-persona#111]
When on small desktops, if I click on the search icon in the header, a search box appears. But, this results in the header menu going on to the next line (which looks kinda ugly). See this screengrab:

![search](https://cloud.githubusercontent.com/assets/1963288/9151912/36b1f23e-3e0d-11e5-9319-2daa8f61b66d.png)

**Comment by pichalite** [comment]
@henrywright Did you change the header menu to display text instead of icons?

**Comment by henrywright** [comment]
@pichalite yes I did but the same applies to a header with icons. See this screenshot of the NobeBB community forum taken on a small desktop:

![forum](https://cloud.githubusercontent.com/assets/1963288/9154557/4bea9cf2-3e8d-11e5-93a6-389b334085d7.png)

**Comment by henrywright** [comment]
Thinking about this, it's probably an issue related to the search plugin, rather than Persona. Feel free to close.
