### ISSUE TITLE
User friendly date formats

### ISSUE THREAD

**Issue by henrywright** [NodeBB/nodebb-theme-persona#115]
Hovering over the "relative time" on each post shows the date of the post in ISO 8601 format (example 2013-12-10T20:23:28Z). A large proportion of my users don't understand the "T" or the "Z". I realise it is difficult to display absolute dates because users will be coming from different time zones but any chance something more user friendly could be used?

https://community.nodebb.org/topic/180/who-is-using-nodebb

**Comment by barisusakli** [comment]
https://github.com/NodeBB/NodeBB/issues/3322
