### ISSUE TITLE
notifications dropdown css breaks on dark themes

### ISSUE THREAD

**Issue by barisusakli** [NodeBB/nodebb-theme-persona#118]
![image](https://cloud.githubusercontent.com/assets/2583394/9337829/a13ada22-45af-11e5-9607-e82d58b563f1.png)

**Comment by barisusakli** [comment]
Post tools dropdown as well

![image](https://cloud.githubusercontent.com/assets/2583394/9344792/38e47738-45d9-11e5-849c-520fd26155ac.png)

**Comment by mrgame64** [comment]
Oh, I can confirm I can reproduce both of them
