### ISSUE TITLE
Groups page not displaying properly

### ISSUE THREAD

**Issue by henrywright** [NodeBB/nodebb-theme-persona#120]
The groups page looks kind of funky. The boxes don't seem to be rendering properly. Not sure if this is since the 0.7.3 upgrade or if it was happening before that. For example: https://community.nodebb.org/user/julian/groups

I'm using the Chromium browser. Here's a screenshot of what I see:

![groups](https://cloud.githubusercontent.com/assets/1963288/9356823/572034e2-467b-11e5-819f-aa7d99612159.png)

**Comment by mrgame64** [comment]
I'm unable to reproduce the issue with NodeBB v0.7.3 and Persona v2.0.13

**Comment by henrywright** [comment]
@mrgame64 could be the browser I'm using. Which browser are you using to test?

**Comment by mrgame64** [comment]
Safari on OSX 10.10

**Comment by henrywright** [comment]
> I'd recommend wiping your browser cache

Just tried that. Still the same for me

**Comment by henrywright** [comment]
@mrgame64 Run [this page](https://community.nodebb.org/user/julian/groups) through a service such as  [URL2PNG](https://www.url2png.com/) and you should see the problem.

**Comment by mrgame64** [comment]
No need to, I'm seeing it directly in my browser when I open the link
