### ISSUE TITLE
P element shouldn't be a child of UL element

### ISSUE THREAD

**Issue by henrywright** [NodeBB/nodebb-theme-persona#132]
Here's a snippet of the markup generated from categories.tpl:

    <ul class="categories" itemscope itemtype="http://www.schema.org/ItemList">
        <p>categories</p>
        <li>...

According to the W3C Validator, `<p>` elements can't be child elements of `<ul>` elements in this context (I have no idea why though?).

Visual:

![cat](https://cloud.githubusercontent.com/assets/1963288/9503915/aab8d044-4c31-11e5-9512-3f2a155862db.png)

**Comment by julianlam** [comment]
Haha it's  because the only child of a `<ul>` should be an `<li>`

**Comment by psychobunny** [comment]
That really should be an H1 anyways, outside the UL

**Comment by henrywright** [comment]
@psychobunny aren't the category titles already `h1`?

**Comment by psychobunny** [comment]
Those should be H2's actually. SEO voodoo suggests you shouldn't have more than a couple of H1's per page

**Comment by henrywright** [comment]
> Those should be H2's actually. SEO voodoo suggests you shouldn't have more than a couple of H1's per page

Ah OK.

Also related to this "illegal child" issue is the category description text.

    <small>
        <p>Check here for announcements about NodeBB</p>
        <div class="row github-embeds-container"></div>
    </small>

Both the `<p>` and `<div>` elements can't be child elements of `<small>`
