### ISSUE TITLE
Move to rem and em units

### ISSUE THREAD

**Issue by henrywright** [NodeBB/nodebb-theme-persona#147]
The current Bootstrap version uses `px` units. Persona also uses `px` units throughout. [Bootstrap 4 alpha](http://blog.getbootstrap.com/2015/08/19/bootstrap-4-alpha/) has just dropped. Looks like they've moved from using `px` to `rem` and `em` units where appropriate. 

This allows typography and page elements to look _great_ visually on all screen sizes.

Requisites:
- Bootstrap upgrade to v4
- Persona .less files overhaul

Would be a big task but entirely worth it in my opinion.

**Comment by julianlam** [comment]
hahaha they're also switching from less to scss, are you going to submit a pull request for that too? :trollface:

**Comment by henrywright** [comment]
Haha! Less, scss, sass... There will most probably be a new one out by next week :laughing:

**Comment by psychobunny** [comment]
Using px has been a great failing of mine personally. 

Happy to get this change rolling. 

My problem is sometimes we just use em without actually testing on mobile, so it's more of a paradigm shift as opposed to a find a replace fix kind of thing @julianlam @barisusakli

**Comment by henrywright** [comment]
I'd be happy to help with this if there's anything that can be done from my end? or an extra pair of hands if you need help testing.

I agree using px units on websites isn't great, especially when you scale to small or large screen sizes.

**Comment by psychobunny** [comment]
This is happening in our next theme which will be based on BS4
