### ISSUE TITLE
A few localization issues

### ISSUE THREAD

**Issue by mrgame64** [NodeBB/nodebb-theme-persona#153]
I'm using the NodeBB v0.8.1 with Persona theme v2.1.25, with the forum language set to *Italian*.

What me and my colleagues have noticed, is that the localization is missing in a few places, like...

"Categories" on the home page
<img width="467" alt="screen shot 2015-09-08 at 13 14 03" src="https://cloud.githubusercontent.com/assets/5879873/9733449/98580240-562b-11e5-879d-52edb892d27a.png">

"See all chats" in the chats menu
<img src="http://puu.sh/k42YM/d10e091bf4.jpg">

"See all notifications" in the notification menu
<img width="307" alt="screen shot 2015-09-08 at 13 20 47" src="https://cloud.githubusercontent.com/assets/5879873/9733561/878fd158-562c-11e5-80e8-6e224aec5be7.png">

"Do not disturb" in the profile menu
![14c51e3edc11ae9a44cc58eada03a47b0fd1bb4d774be83633 pimgpsh_fullsize_distr](https://cloud.githubusercontent.com/assets/5879873/9733634/49df18b8-562d-11e5-977a-0d6d8618a9b2.png)

...and the "Views" count in every topic being wrongly positioned...
<img src="http://puu.sh/k42Qi/2c47ab15b9.png">
...as it should look like this:
<img src="http://puu.sh/k42Ta/2bf9203021.png">

**Comment by mrgame64** [comment]
We've also noticed that in many cases the page's title is not being correctly localized as well.

**Comment by barisusakli** [comment]
This isnt a theme problem, they should be translated in transifex if not already done.

**Comment by mrgame64** [comment]
I'm pretty sure the last thing is actually a theme issue, as it's not related to translation

**Comment by barisusakli** [comment]
The text centering issue should be resolved in the above commit.
