### ISSUE TITLE
[Mobile only] CSS forces background to white, disregarding the Bootswatch skin

### ISSUE THREAD

**Issue by mrgame64** [NodeBB/nodebb-theme-persona#156]
The culprit seems to be `background-color: #fff` for `#panel`.
It affects only mobile & resized desktop windows, full-sized desktop is just fine.

**Comment by bdharrington7** [comment]
+1

**Comment by julianlam** [comment]
That's a little weird, why does the panel have a white background, and what if it is set to `rgba(0,0,0,0);`?

**Comment by barisusakli** [comment]
#panel {
		background: @body-bg;
		min-height: 100%;
		padding-top: 80px;
	}

@body-bg doesn't work with bootswatch

**Comment by pitaj** [comment]
This is for the mobile slide-in menu.
