### ISSUE TITLE
Use bookmark icon instead of star for bookmarks

### ISSUE THREAD

**Issue by psychobunny** [NodeBB/nodebb-theme-persona#169]
https://community.nodebb.org/topic/6719/star-icon-appears-then-disappears/5

**Comment by barisusakli** [comment]
https://github.com/NodeBB/nodebb-theme-persona/commit/5c9e7c3c49cdeefd5f95ca81adb6e3370d58b612 :trollface:

**Comment by psychobunny** [comment]
What is this sorcery, fixing bugs before its issued
