### ISSUE TITLE
Role attribute on nav element not needed

### ISSUE THREAD

**Issue by henrywright** [NodeBB/nodebb-theme-persona#179]
According to the W3C, `nav` elements don't need a role attribute. See this screenshot of the W3C Validator results:

![w3c-validator](https://cloud.githubusercontent.com/assets/1963288/10788532/125a5172-7d70-11e5-8a8b-33dc7f13aa03.png)

**Comment by psychobunny** [comment]
From the Bootstrap docs:

```
Make navs used as navigation accessible

If you are using navs to provide a navigation bar, be sure to add a role="navigation" to the most logical parent container of the <ul>, or wrap a <nav> element around the whole navigation. Do not add the role to the <ul> itself, as this would prevent it from being announced as an actual list by assistive technologies.
```

I'm not sure actually tbh, they've changed their syntax for <nav> since we first built the theme

**Comment by henrywright** [comment]
> If you are using navs to provide a navigation bar, be sure to add a role="navigation" to the most logical parent container of the <ul>, 

I think the key word here is _logical_. The role attribute allows the author to annotate the markup with info about the purpose of an element. I think `<nav>` elements by their very name already convey this semantic info. 

> or wrap a <nav> element around the whole navigation. 

This, in my view, is what should be done, as implemented by this PR.

But of course, that's just my interpretation of it (which may easily be wrong because the guidelines can be confusing!).
