### ISSUE TITLE
After posting, mobile sidebar is inaccessible

### ISSUE THREAD

**Issue by julianlam** [NodeBB/nodebb-theme-persona#18]
![screenshot_2015-03-24-07-30-52_1024](https://cloud.githubusercontent.com/assets/923011/6800790/3fab37a0-d1f8-11e4-97b0-33c1237e5fc6.png)

**Comment by psychobunny** [comment]
I can't reproduce this, at least on latest

**Comment by julianlam** [comment]
Me neither, possibly fixed in the slew of other commits.
