### ISSUE TITLE
Uploaded group covers missing on mobile

### ISSUE THREAD

**Issue by psychobunny** [NodeBB/nodebb-theme-persona#185]
https://community.nodebb.org/groups/anime-lovers

**Comment by henrywright** [comment]
Just to add, the image isn't quite "missing". The height is just reduced so you can't see it at tiny screen sizes. If you resize your desktop browser you should see what I mean.

I think `background-size: cover;` could be the problem.

**Comment by psychobunny** [comment]
The actual problem was that the banner was set to -277px (with the drag to reposition function). Which is fine on desktop, but then disappears on mobile. I'm thinking I should force `background-position: 0` on mobile

**Comment by psychobunny** [comment]
nvm, everything is done in % now instead of px. Repositioning that image fixed it

**Comment by henrywright** [comment]
> everything is done in % now instead of px

Nice! Sounds like a far better way of doing it. Positioning in pixels feels hackish to me :)
