### ISSUE TITLE
Viewing group header images on mobile

### ISSUE THREAD

**Issue by henrywright** [NodeBB/nodebb-theme-persona#186]
This particular group's header image doesn't display properly on mobile at portrait orientation. The screenshot below shows an example of what I'm seeing using Chrome.

https://community.nodebb.org/groups/anime-lovers

![screenshot 2015-10-30 at 12 12 20](https://cloud.githubusercontent.com/assets/1963288/10845446/cfa7ee3e-7eff-11e5-80c3-b7c19550da06.png)

**Comment by MegaGM** [comment]
@henrywright https://github.com/NodeBB/nodebb-theme-persona/issues/185

**Comment by henrywright** [comment]
@MegaGM I should have looked through existing issues first :)
