### ISSUE TITLE
Hover cards don't work with dynamically added user pictures

### ISSUE THREAD

**Issue by pitaj** [NodeBB/nodebb-theme-persona#189]
It's because [the `setupHoverCards` function](https://github.com/NodeBB/nodebb-theme-persona/blob/master/lib/persona.js#L166-L171) only runs on page load, so only user picture available on page load have the hover effect.

Fix it like this:

```js
	function setupHoverCards() {
		$('.topic').on('mouseover', '[component="user/picture"]', generateUserCard);
	}
```

**Comment by psychobunny** [comment]
https://github.com/NodeBB/nodebb-theme-persona/issues/184

L2R issues. Just kidding, your issue is more concise. I am aware :)

**Comment by psychobunny** [comment]
I prefer to use the hook on new posts though

**Comment by pitaj** [comment]
But, but this is so much better. You don't have to worry about dynamic content at all!
