### ISSUE TITLE
Unable to Reach Settings in Some Browsers

### ISSUE THREAD

**Issue by scottalanmiller** [NodeBB/nodebb-theme-persona#199]
https://community.nodebb.org/topic/6942/user-account-settings-only-working-in-chrome

Screenshots there.  Our install has the backround not extending to where the settings button is and the button is often either unclickable or the resulting menu is off screen.

**Comment by sorvani** [comment]
The embedded ad is the likely cause: http://mangolassi.it/topic/6769/ability-to-reach-the-settings-button

**Comment by scottalanmiller** [comment]
A bug would be the cause.  The ad is just an image in the global sidebar.  It would only be the "cause" if the widget system is not supported.  The use of the widget system might trigger it but any theme, especially the official one,should properly support the base platform, correct?  So the cause would still be a flaw in the theme.  The global sidebar is being used as designed.

**Comment by sorvani** [comment]
The embedded ad is the item that is likely different that is causing the bug to manifest. Happy now with the phasing?
