### ISSUE TITLE
Profile page showing avatar over name

### ISSUE THREAD

**Issue by sorvani** [NodeBB/nodebb-theme-persona#202]
On the mangolassi.it community, the profile page is showing the avatar over the top of the name.

![img](http://i.imgur.com/HSnsZx4.jpg)

**Comment by manV** [comment]
Having same issue in presence of sidebar widget 
![screenshot from 2015-11-16 19-59-00](https://cloud.githubusercontent.com/assets/4988376/11184284/bdc2ff74-8c9c-11e5-9d0e-1e361192a8b2.png)

**Comment by julianlam** [comment]
Should have been resolved in latest Persona already. Try master or wait for
v0.9.1. Thanks!

**Comment by manV** [comment]
@julianlam took this screenshot using persona 4.0.36

**Comment by julianlam** [comment]
![image](https://cloud.githubusercontent.com/assets/923011/11192895/888033e8-8c71-11e5-856c-c5850983550c.png)

Looks good here, are you on latest `master` as well?

**Comment by sorvani** [comment]
I am seeing this fixed on the current master on my new site.

**Comment by manV** [comment]
Sorry, I was on theme's latest master, not nodebb. upgraded nodebb to latest master and now it works. Thanks.
