### ISSUE TITLE
the profile menu is on the left

### ISSUE THREAD

**Issue by sorvani** [NodeBB/nodebb-theme-persona#204]
I just installed a new board and everything seems to be working normal except for the profile settings button being on the left. I pulled the master branch of nodebb just now and reloaded to make sure I was current

![img](http://i.imgur.com/GjMeqqm.jpg)

**Comment by sorvani** [comment]
I should state, I have no idea where to look to even troubleshoot this.

I am using nodebb/master pulled as of last night.

**Comment by barisusakli** [comment]
This happens if a bootswatch skin is used

**Comment by sorvani** [comment]
What is a skin that does not? So I can switch my forum default ?

**Comment by barisusakli** [comment]
Click the revert button on ACP>Appearance>Skins. It is located on the bottom right.

**Comment by sorvani** [comment]
That button apparently does not work in Chrome Version 46.0.2490.86 m. The revert button works on the Theme page, but not the skin. I went to Firefox and the button worked, reverted to base colors.
