### ISSUE TITLE
Mobile menu doesn't appear 

### ISSUE THREAD

**Issue by enric612** [NodeBB/nodebb-theme-persona#205]
I try to to show mobile menu in mobile (android, miui, cyanogen... using chrome and stock browser) and in browser at WIndows/Linux PC (Chrome and FIrefox). When i press nothing happens.
Can you help me in that?
Thanks!

**Comment by Dynosore** [comment]
Way too late to be of assistance to you, but for anyone else with a similar issue that finds this, I reset everything with `./nodebb reset` and this still didn't correct my issue. I came to realize that there was an issue with the Cerulean Skin. Changing the skin off of cerulean, then back onto it corrected my issue.
