### ISSUE TITLE
Change picture modal window error

### ISSUE THREAD

**Issue by pichalite** [NodeBB/nodebb-theme-persona#206]
Go to User -> Edit page, click on "Change Picture". Close the modal window.

Hard refresh the page. Progress bar on the top doesn't stop loading and clicking on "Change Picture" does not work anymore. There is some error in the browser console.

**Comment by barisusakli** [comment]
For reference this was caused because the contents of `<script id="ajaxify-data"></script>` was being translated and it was resulting in invalid json.
