### ISSUE TITLE
modal hidden on groups

### ISSUE THREAD

**Issue by martyalicante** [NodeBB/nodebb-theme-persona#210]
![captura de pantalla 2015-11-27 a las 21 10 25](https://cloud.githubusercontent.com/assets/10746278/11447724/7a213152-954b-11e5-8896-164f4d6312b9.png)

**Comment by julianlam** [comment]
Likely resolved. Report theme versions?

**Comment by martyalicante** [comment]
0.9.1 just installed
persona 4.0.37
