### ISSUE TITLE
dropdown RTL issue

### ISSUE THREAD

**Issue by MohamadSH** [NodeBB/nodebb-theme-persona#216]
Hi, I faced this bug in the lay out:
After I login to my account I see my avatar on the top left corner of the page. When I click on my avatar a box appears which includes my email address and my available statuses and a log out link. The problem is that I can see only half of the box and it seems the rest of it is out of the page. I have uploaded a photo of this issue. I hope you don't mind that the language in the photo is not english:
![screenshot](https://cloud.githubusercontent.com/assets/15714168/11836194/436fa5f6-a3ee-11e5-8882-0914466b925b.png)

**Comment by psychobunny** [comment]
Makes sense, since RTL but our CSS floats the dropdown left. We can probably fix this with some CSS rules. 

There might be other locations with the same problem, can you please check and report here? Thanks

**Comment by barisusakli** [comment]
This seems fixed
![image](https://user-images.githubusercontent.com/2583394/46779207-d1d7f100-cce4-11e8-9d1e-3d4911a51ec5.png)
