### ISSUE TITLE
Shrink post editor button not working all the time

### ISSUE THREAD

**Issue by whittssg** [NodeBB/nodebb-theme-persona#221]
The Button that allows you to shrink and expand the post editor (black circle with white chevron down icon) doesnt seem to work consistently.

When i first open the editor (the editor is expanded) i click the button and the editor will move down like 1/2 cm. if i click it again it will move backup half a cm. After a few clicks it starts working as expected and if i keep the site open it always works till the next time i open the site.. Thanks

On the latest version

**Comment by pichalite** [comment]
This is most likely a problem with the nodebb-plugin-composer-default plugin.
