### ISSUE TITLE
Theme problem with RTLs (in some parts)

### ISSUE THREAD

**Issue by MohamadSH** [NodeBB/nodebb-theme-persona#224]
Hi,
I just wanted to inform you that some parts of your them have problem with RTLs and we have fixed it through custom CSS on admin panel. We were wondering if you could fix this issue in the theme itself.
CSS parts that we have changed are:
# user-control-list li, .notification-list li, .header .chat-list li{

```
    text-align: right !important;
```

}
.dropdown-menu li  {
        text-align: right ;
}

Thanks a lot.

**Comment by psychobunny** [comment]
Thanks, Can you submit a pull request please?

**Comment by MohamadSH** [comment]
What I meant is that after finding what modification we need to do to make it right(through inspect element), we have customized NodeBB css through admin panel > appearance > custom css . Actually without this feature of NodeBB we couldn't do this. My request is fixing this in the css core so it will become more convenient for anyone with a RTL language .

**Comment by julianlam** [comment]
Looks like this is already done in the interim :smile:
