### ISSUE TITLE
User icons in groups>memberlist do not have same size

### ISSUE THREAD

**Issue by pichalite** [NodeBB/nodebb-theme-persona#227]
Images are 32x32 with radius at 50%..... user icons are 24x24

![image](https://cloud.githubusercontent.com/assets/10014774/12567901/c855a3ae-c376-11e5-8bd5-cff02ccbf3b5.png)

**Comment by barisusakli** [comment]
https://github.com/NodeBB/nodebb-theme-persona/commit/60fbd803b566700b1b65922db1cda668c6bda9a9
