### ISSUE TITLE
Chat close/fullscreen icons not displaying on IE 11 and Chrome on Win 7

### ISSUE THREAD

**Issue by jeffbski** [NodeBB/nodebb-theme-persona#228]
The chat floating window close and full-screen icons do not show up on IE 11 and Chrome using Windows 7.

OS: Windows 7 Service Pack 1
IE: 11.0.9600.18163
Chrome: 47.0.2526.111

Maybe it is because a certain css property is not supported to do the greying effect for those icons?

You can click them if you know where they are and just click blindly.

This is all using the NodeBB master at commit 4440865 which is fairly recent.

I am using the default layout Persona and default skin.

Below is a screenshot of the floating chat in IE 11 without the close, full-screen icons

![chat-dialog](https://cloud.githubusercontent.com/assets/5689/12685723/9875fa04-c68b-11e5-87cf-542f1795c2c8.png)

**Comment by pichalite** [comment]
cannot reproduce this on windows 7 using chrome or IE 11.
