### ISSUE TITLE
Since theme doesn't support chat fullscreen at smaller sizes, full-screen icon should be hidden

### ISSUE THREAD

**Issue by jeffbski** [NodeBB/nodebb-theme-persona#229]
@pichalite informed me that Persona doesn't support fullscreen chat at smaller window sizes, so we should probably hide the full-screen icon at the smaller sizes, so users won't be confused when they click on it and it doesn't do what they would expect.

https://github.com/NodeBB/NodeBB/issues/4128#issuecomment-176917798

**Comment by pichalite** [comment]
@jeffbski you got the screen sizes the other way. fullscreen chat is only supported on larger screen sizes.

**Comment by jeffbski** [comment]
oops misunderstood. I'll fix the issue.

**Comment by jeffbski** [comment]
Just for completeness to help visualize the problem, here is a screenshot after clicking full-screen chat at a smaller window size, it doesn't allow viewing of the chat details and replying.

Once a user clicks full-screen they can't interact with the chat, nor can they revert the action, they have to re-enter the chat again. It also is confusing since they will accidentally click the close x for the chat room and that takes them out of the chat altogether rather than simply reverting to non full-screen. 

Thus the user gets confused since they didn't even know what happened and now they aren't in the chats anymore.

So definitely is a UX issue.

![chat-full-screen](https://cloud.githubusercontent.com/assets/5689/12686144/c315e77c-c68d-11e5-8ac8-be939a4c6547.png)

**Comment by pichalite** [comment]
this is already fixed here https://github.com/NodeBB/nodebb-theme-persona/blob/master/templates/chat.tpl#L8

can be closed.
