### ISSUE TITLE
The page could not show well ,

### ISSUE THREAD

**Issue by xusai2014** [NodeBB/nodebb-theme-persona#231]
![image](https://cloud.githubusercontent.com/assets/8156165/12777696/8172f598-ca99-11e5-9256-ee691bfe3dca.png)

##The log

**Clustering enabled: Spinning up 1 process(es).

3/2 09:01 [23859] - info: Time: Wed Feb 03 2016 09:01:08 GMT+0000 (UTC)
3/2 09:01 [23859] - info: Initializing NodeBB v0.9.3
3/2 09:01 [23859] - info: [database] Checking database indices.
3/2 09:01 [23859] - warn: [socket.io] Clustering detected, you are advised to configure Redis as a websocket store.
3/2 09:01 [23859] - info: NodeBB Ready
3/2 09:01 [23859] - info: Enabling 'trust proxy'
3/2 09:01 [23859] - info: NodeBB is now listening on: 0.0.0.0:7092
**

**Comment by psychobunny** [comment]
Do you have any plugins installed? What's your NodeBB hash (run `git rev-parse HEAD`) and version of persona?
