### ISSUE TITLE
Account Menu: best, upvoted and downvoted not working

### ISSUE THREAD

**Issue by alexschomb** [NodeBB/nodebb-theme-persona#235]
I just updated to latest release from here, because NodeBB displays the months old v4.0.45 as the newest version of nodebb-theme-persona. Unfortunately I found the new "best", "upvoted" and "downvoted" links in the account menu lead to dead links. The links aren't localized as well. Is this happening only to me or shouldn't these links be part of the releases?

The relevant file I'm talking about is  ```templates/partials/account/menu.tpl```

**Comment by julianlam** [comment]
The version of Persona is tied to your NodeBB version. Only the one listed in `package.json` should be installed. If you want to use a newer version of Persona, you'll need to update NodeBB itself.
