### ISSUE TITLE
user-avatar border-radius

### ISSUE THREAD

**Issue by frissdiegurke** [NodeBB/nodebb-theme-persona#24]
you've been using 50% border-radius for user-avatars for long now (as I remember since cerulean or vanilla early days).
since this is a pretty non-standard way of doing I'd propose not do do so anymore in a such-lightweight theme this should be.
Personally I've never been a friend of this round avatars this is why I come up with it...
Maybe you could start a poll about this if you're not seeing my point.
Or maybe there should be an option to toggle between border-radius `50%`/`@border-radius-base`/`0`/`theme-preference` within core ACP.

**Comment by cnvo** [comment]
50%? I use 100% or 999em. I also don't see this being configurable in the ACP at all. Perhaps creating your own mixin would be the best solution in this case.

**Comment by julianlam** [comment]
Doesn't bootstrap have a class for adding `border-radius: 50%;`? We should just be using that class instead of putting it in theme. If it's already this way, then this is a moot issue as it can be changed easily in child themes.

**Comment by frissdiegurke** [comment]
@julianlam I don't know whether bootstrap has such a class. But in my opinion this is no decision the theme should completely decide about. The more I think about it the more i'd like to have an option within the ACP (and maybe a new entry within the theme.json to set theme-preference) to allow the admin to decide which one to use without having to know LESS.

@cnvo I've just checked, 50% seems to be enough and it's even more plausible than 100% if you think about it ;)

**Comment by julianlam** [comment]
Putting it as an ACP option also doesn't seem right because then there's no strict separation between the theme and the forum logic...

Perhaps we could add it as a toggle-able option in a dedicated "Persona" ACP page.

**Comment by psychobunny** [comment]
![](http://i.imgur.com/txVTiA2.png)

Put this in your ACP -> Appearance -> Custom HTML & CSS

```
.icon, .img-circle {
    border-radius: 0%!important;   
}
```

For this theme specifically, it will cover all your bases. ACP option is out of scope for this theme, but I won't forget about it when I start thinking about theme-based control panel options in future
