### ISSUE TITLE
Redesign register/login pages

### ISSUE THREAD

**Issue by psychobunny** [NodeBB/nodebb-theme-persona#242]
It's something I've been wanting to do for a long time... it really hasn't changed much since the first few months after we started NodeBB. Related issue: https://github.com/NodeBB/NodeBB/issues/3305

**Comment by pichalite** [comment]
Implemented here https://github.com/NodeBB/nodebb-theme-persona/pull/315 and here https://github.com/NodeBB/nodebb-theme-persona/pull/316
