### ISSUE TITLE
Profile popover and YouTube

### ISSUE THREAD

**Issue by nhlpl** [NodeBB/nodebb-theme-persona#243]
https://community.nodebb.org/topic/7997/testing-yt-embed

![popover](https://cloud.githubusercontent.com/assets/11160550/13337378/4ef8319e-dc1b-11e5-9c54-f6d13dcf2c2c.jpg)

**Comment by julianlam** [comment]
User card has `z-index` of `1`, `html5-info-bar` has a `z-index` of `935`.

@a5mith Not sure why it needs a z-index, could you remove it?
