### ISSUE TITLE
Strong dependency on nodebb-plugin-recent-cards should be removed

### ISSUE THREAD

**Issue by globalcow** [NodeBB/nodebb-theme-persona#247]
When deactivating the plugin nodebb-plugin-recent-cards, the headline 'Recent topics' is still visible and it is not possible to just hide it via CSS. So it is not easy to run the the theme without this plugin.

**Comment by psychobunny** [comment]
Hmm did you restart? (A reload may not work)

**Comment by globalcow** [comment]
No, this will not solve the problem. The headline 'Recent topics' is always visible. I attached a sceenshot. The yellow part is visible although I deactivated the plugin. By the way, the string 'Recent topics' is not translated. ![persona](https://cloud.githubusercontent.com/assets/2294737/13527235/f5b3940e-e20d-11e5-88b4-fa2114acc627.PNG)

**Comment by pichalite** [comment]
I can confirm... `./nodebb restart` or "Restart" from ACP does clear the "Recent Topics" heading.

**Comment by globalcow** [comment]
Sorry guys, you are right! I had to restart my service to do a real restart.
