### ISSUE TITLE
mobile side menu should close on selection

### ISSUE THREAD

**Issue by barisusakli** [NodeBB/nodebb-theme-persona#25]
no?

**Comment by psychobunny** [comment]
heh. I'll give you $5 if you can make this work on mobile

Unfortunately I might have to rewrite the menu :dull: the ajaxify animation blocks the menu animation on mobile.

**Comment by psychobunny** [comment]
> EDIT: this is pretty much the reason why it doesn't close on click right now, I wanted to do it, it doesn't work very smoothly

And when you add the ajaxify bar animation: 

![](http://images.huffingtonpost.com/2014-10-29-CHALLENGEREXPLOSION.jpg)

**Comment by barisusakli** [comment]
Hmm I think we did it for lavender no? We just trigger a click on the menu button as if the user clicked on it.

**Comment by psychobunny** [comment]
lav doesn't have 3d translation, menu just collapses over the content. current is entire body gets shifted over

if I use regular css (ex. margin-left transition) to move the entire body well that will explode on mobile too

**Comment by a5mith** [comment]
I've found the most intuitive sidebar menu is the one in the spotify mobile app. It's such a nice experience to use Rather than shifting all content etc, it should probably just overlay, then close on a selection. :) what's the exchange rate on 2 cents these days. :p

**Comment by psychobunny** [comment]
Canadian? We phased out cents last year, so you'll have to round that down please

**Comment by a5mith** [comment]
Does your currency start at dollar now then? :laughing:

**Comment by julianlam** [comment]
I'm actually a bit unclear on how automatically firing a click event on the "hamburger button" would adversely affect the animation... they're separate systems, aren't they?

**Comment by psychobunny** [comment]
Haha reassigned to Julian

**Comment by julianlam** [comment]
... but clearly I don't even understand the problem! 

Reassigned back to @psychobunny :trollface:

**Comment by cnvo** [comment]
Ohh, I had to really read the whole thread to understand what you're looking for here. Lol. I forked the theme and are going through it now. :)

**Comment by a5mith** [comment]
So, is this not being done then? :)

**Comment by barisusakli** [comment]
Its done in core for now.

**Comment by a5mith** [comment]
Ah right, nice one. :+1:
