### ISSUE TITLE
Doubled topic title after using guest handles

### ISSUE THREAD

**Issue by nhlpl** [NodeBB/nodebb-theme-persona#254]
NodeBB 1.0.1 version, v1.x.x branch, fresh install
Persona 4.0.99
Lavender & Vanilla looks good

Allowed guests to reply to topics in this category and reverted to default.
Opening topic and using browser's back button renders it correctly (subtitle disappears).

Tested it again and can reproduce it for many times.
It breaks after enabling and disabling Allow guest handles 

![subt](https://cloud.githubusercontent.com/assets/11160550/13901287/b95de6ae-ee1e-11e5-96e7-f84f4390dd83.jpg)

![subt2](https://cloud.githubusercontent.com/assets/11160550/13901341/9b4476e0-ee20-11e5-81f5-b5a68c8c45e4.jpg)

**Comment by pichalite** [comment]
cannot reproduce on latest
