### ISSUE TITLE
Selecting topic to be deleted

### ISSUE THREAD

**Issue by nhlpl** [NodeBB/nodebb-theme-persona#258]
NodeBB 1.0.2 version, v1.x.x branch, fresh install

Low priority

Steps to reproduce:
1) Go to General Discussion category
2) Click avatar neat to Welcome to your NodeBB!
3) Topic Tools > Delete Topic > OK
4) Avatar is still checked (see image below)

![avatdel](https://cloud.githubusercontent.com/assets/11160550/13946211/8f1d0a0e-f013-11e5-9d99-5e4247ffe800.jpg)

**Comment by pichalite** [comment]
I think this is by design to facilitate easy purging right after deleting.
