### ISSUE TITLE
Menu messed up after navigating to new page 

### ISSUE THREAD

**Issue by julianlam** [NodeBB/nodebb-theme-persona#26]
![](http://i.imgur.com/mFJjZtW.png) 

Possibly I tapped one too many times... will try to reproduce

**Comment by psychobunny** [comment]
Mm, you'd have to push latest I couldn't repro locally but I could on try yesterday

**Comment by julianlam** [comment]
Ok, great, thanks!

**Comment by julianlam** [comment]
Seems resolved after d5a8d3b374742f0825e62ea914c3b5392927b825

**Comment by julianlam** [comment]
:trollface: Sorry

![](http://www.imgur.com/vjB3r29.png) 

Reproduced when I hit the menu button during ajaxification

**Comment by mrgame64** [comment]
I've seen someone having the same problem on Windows Phone
![1a2988ee-cf2e-4305-b0d0-b843c883b0d9](https://cloud.githubusercontent.com/assets/5879873/9021796/202487d6-3857-11e5-886f-db674bb25c97.jpg)

**Comment by barisusakli** [comment]
Re open if you can still repro
