### ISSUE TITLE
Line breakers

### ISSUE THREAD

**Issue by nhlpl** [NodeBB/nodebb-theme-persona#262]
I'm preatty sure you've already seen this here and on TDWTF.
https://community.nodebb.org/topic/8351/ส-_-ツ-_ส-line-breakers/2

It renders okay on Unread page and breaks on Recent page.

![linebreakers](https://cloud.githubusercontent.com/assets/11160550/13990947/847eae32-f116-11e5-9d3a-d6ebd675aa02.jpg)

**Comment by barisusakli** [comment]
Needs to be fixed incomposer as well
