### ISSUE TITLE
Composer disappears

### ISSUE THREAD

**Issue by bdharrington7** [NodeBB/nodebb-theme-persona#272]
When starting to compose a reply in iOS Safari, the composer window scrolls out of view, causing a lot of confusion. A good description of the behavior has been reported here:

https://github.com/NodeBB/NodeBB/issues/4409

**Comment by huegelc** [comment]
Yes, I have the same issue on Android with Firefox/Chrome https://community.nodebb.org/topic/8863/persona-input-field-disappears-on-mobile-devices/2

**Comment by pichalite** [comment]
@bdharrington7 give the new version of the composer a try. It's available on https://community.nodebb.org if you want to try.

**Comment by pichalite** [comment]
this can be closed?

**Comment by bdharrington7** [comment]
I would consider it closed. Thanks @pichalite!

**Comment by huegelc** [comment]
@pichalite where exactly is this thread?

**Comment by pichalite** [comment]
@huegelc thread about what?

**Comment by huegelc** [comment]
@pichalite now I uderstand: you mean the new composer version is integrated in the community nodebb forum. Sorry
