### ISSUE TITLE
Categorie images are broken after enabling persona

### ISSUE THREAD

**Issue by remcokatz** [NodeBB/nodebb-theme-persona#28]
I'm unable to delete categorie images that were set before enabling the persona theme. It's also impossible to get images working on new categories even when using font-awesome icons.

**Comment by remcokatz** [comment]
![bug](https://cloud.githubusercontent.com/assets/11693521/6880891/dec827bc-d545-11e4-9e1f-51e35959702d.gif)

Printing: Pre-existing categorie
Testing: New categorie after installing persona

**Comment by MegaGM** [comment]
Hello @remcokatz, thank you for reporting!
The bug was solved in https://github.com/NodeBB/NodeBB/pull/2908
Update your NodeBB to latest master via `git pull`

---
Please let us know if you'll encounter any more bugs!

**Comment by MegaGM** [comment]
Hello @remcokatz, thank you for reporting!
The bug was solved in https://github.com/NodeBB/NodeBB/pull/2908
Update your NodeBB to latest master via `git pull`

---
Please let us know if you'll encounter any more bugs!

**Comment by remcokatz** [comment]
Perfect! Deleting images and uploading new ones now works.

I am, unfortunately, not able to select a new icon yet. I can click on the image section from which I get the icon popup. After selecting the icon I'd want (1 click OR double click) and clicking save it will not show the icon.

**Comment by julianlam** [comment]
Should be resolved in core now
