### ISSUE TITLE
Two headers on topic pages

### ISSUE THREAD

**Issue by BenLubar** [NodeBB/nodebb-theme-persona#281]
There are two header widget areas on topic pages.

This is the sixth duplicate bug report, but this time it's in the right place:

1. https://what.thedailywtf.com/topic/20032/uh-guys-uh-guys
2. https://what.thedailywtf.com/topic/20034/what-what
3. https://what.thedailywtf.com/post/899670
4. https://what.thedailywtf.com/post/899682
5. https://github.com/apapadimoulis/what-bugs/issues/132
6. This one!

/cc @halcyon1234 @blakeyrat-dailywtf @devjoe2

**Comment by julianlam** [comment]
@yariplus :wink: if I don't get to it in time...

**Comment by yariplus** [comment]
omg, I need to lay off the sauce.
