### ISSUE TITLE
Sidebar doesn't opens

### ISSUE THREAD

**Issue by ReyKoxha** [NodeBB/nodebb-theme-persona#298]
Title says it all. Check this link for a video:
https://sendvid.com/h1jd07v2

**Comment by ReyKoxha** [comment]
The sidebar opens up in Mozilla, but closes after you have scrolled a bit.

**Comment by julianlam** [comment]
Closed as the video doesn't work and due to inactivity 😄  Let us know if the issue persists. Thanks.
