### ISSUE TITLE
Menu bar is broken on latest NodeBB

### ISSUE THREAD

**Issue by astr0skillz** [NodeBB/nodebb-theme-persona#30]
Hi,

As per NodeBB 0.6.1, the menu bar seems to be completely broken. Using the latest version of Persona, though the admin interface already mentioned there could be problems due to incompatibility.

![Image]
(http://i.affixes.io/8rj6qgmiav.png)

Thanks.

**Comment by julianlam** [comment]
I'm pretty sure the Persona theme is not tested against v0.6.x, and may be v0.7.0 compatible only...

**Comment by astr0skillz** [comment]
Hmm... I'm not sure where I can find v0.7.0 though. I've tried upgrading to the latest git, though I still seem to be on 0.6.1

**Comment by julianlam** [comment]
You can grab 0.7.0 (the in-development version) from the `master` branch

**Comment by astr0skillz** [comment]
Getting the following error when using that master branch:
```
module.js:356
  Module._extensions[extension](this, filename);
                               ^
Error: /home/webserver/web/blockify.us/public_html/forums/node_modules/mmmagic/build/Release/magic.node: undefined symbol: node_module_register
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/webserver/web/blockify.us/public_html/forums/node_modules/mmmagic/index.js:3:13)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
```

**Comment by julianlam** [comment]
Seems like a dependency issue. Please run `npm rebuild`

**Comment by astr0skillz** [comment]
Same error. Did get this though:

npm WARN unmet dependency /home/webserver/web/blockify.us/public_html/test/node_modules/socket.io-client/node_modules/engine.io-client requires debug@'1.0.4' but will load
npm WARN unmet dependency /home/webserver/web/blockify.us/public_html/test/node_modules/socket.io-client/node_modules/debug,
npm WARN unmet dependency which is version 0.7.4
npm WARN unmet dependency /home/webserver/web/blockify.us/public_html/test/node_modules/socket.io-client/node_modules/engine.io-client requires parseuri@'0.0.4' but will load
npm WARN unmet dependency /home/webserver/web/blockify.us/public_html/test/node_modules/socket.io-client/node_modules/parseuri,
npm WARN unmet dependency which is version 0.0.2

**Comment by astr0skillz** [comment]
Updated both. Still getting the same error:

xxx@xxx:~/web/blockify.us/public_html/forums$ ./nodebb setup
29/3 15:11 [1266] - info: NodeBB v0.7.0-dev Copyright (C) 2013-2014 NodeBB Inc.
29/3 15:11 [1266] - info: This program comes with ABSOLUTELY NO WARRANTY.
29/3 15:11 [1266] - info: This is free software, and you are welcome to redistribute it under certain conditions.
29/3 15:11 [1266] - info: 
29/3 15:11 [1266] - info: NodeBB Setup Triggered via Command Line
29/3 15:11 [1266] - info: Welcome to NodeBB!
29/3 15:11 [1266] - info: This looks like a new installation, so you'll have to answer a few questions about your environment before we can proceed.
29/3 15:11 [1266] - info: Press enter to accept the default setting (shown in brackets).
URL used to access this NodeBB (http://blockify.us/forums) 
Please enter a NodeBB secret (xxx) 
Which database to use (redis) 

29/3 15:11 [1266] - info: Now configuring redis database:
Host IP or address of your Redis instance (127.0.0.1) 
Host port of your Redis instance (6379) 
Password of your Redis database 
Which database to use (0..n) (0) 
29/3 15:11 [1266] - info: Configuration Saved OK
connect-redis@2.0.0 node_modules/connect-redis

redis@0.10.3 node_modules/redis
29/3 15:11 [1266] - info: Populating database with default configs, if not already set...

module.js:356
  Module._extensions[extension](this, filename);
                               ^
Error: /home/webserver/web/blockify.us/public_html/forums/node_modules/mmmagic/build/Release/magic.node: undefined symbol: node_module_register
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/webserver/web/blockify.us/public_html/forums/node_modules/mmmagic/index.js:3:13)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)

**Comment by psychobunny** [comment]
hi, by any chance are you the user who has posted here? https://community.nodebb.org/topic/4108/nodebb-0-7-0-dev-fails-to-install

If you're the OP, another user ran into this problem and would like to know what you did with your npm/node versions to fix it

Thanks!

**Comment by psychobunny** [comment]
if you're still having troubles, please re-file on NodeBB core tracker since this is unrelated to theme
