### ISSUE TITLE
Reposition of cover image cannot be saved

### ISSUE THREAD

**Issue by nuala-louise** [NodeBB/nodebb-theme-persona#303]
When on the users profile page, it allows you to reposition the cover image and tells you to click the save button when you have it in the desired position. However there is no save button so the image repositions itself back to the initial position :( 

Thanks :)

**Comment by julianlam** [comment]
Can you attach a screenshot of the entire cover photo area, including the NodeBB header bar?

**Comment by Wardormeur** [comment]
Our bad @julianlam, our fork add up a new navigation row and was hiding the save button. Thanks for the hint :)

**Comment by pichalite** [comment]
Can be closed?

**Comment by julianlam** [comment]
Thanks @pichalite
