### ISSUE TITLE
Global Header Widget Position Inconsistent

### ISSUE THREAD

**Issue by deiden26** [NodeBB/nodebb-theme-persona#311]
The position of header widgets in this theme is inconsistent. Sometimes the breadcrumbs are above the widgets in the header. Sometimes the breadcrumbs are below.
## ![screen shot 2016-08-19 at 4 14 44 pm](https://cloud.githubusercontent.com/assets/2993523/17826722/99e18470-6628-11e6-915a-92ee9f7128a6.png)

![screen shot 2016-08-19 at 4 15 07 pm](https://cloud.githubusercontent.com/assets/2993523/17826725/99e304c6-6628-11e6-9719-b381498bbaa6.png)

**Comment by Danor** [comment]
Just need to switch two lines of code in: **category.tpl**, **categories.tpl** and **topic.tpl**:

```
<!-- IMPORT partials/breadcrumbs.tpl -->
<div widget-area="header"></div>
```

**Comment by julianlam** [comment]
This doesn't seem right... there are only three matches for `widget-area="header` in `templates/`, meaning these are header widgets for the categories/category/topic pages only, and _not_ the global header.

The global header, meanwhile, *is* on top of everything else 😄
