### ISSUE TITLE
Users - Invite not working consistently

### ISSUE THREAD

**Issue by davidfnmyers** [NodeBB/nodebb-theme-persona#313]
I've been having issues with the invite button not really responding properly on any browser. On iOS / Chrome I can randomly tap around the button and it will eventually work. I also experienced the same behavior on OS X / Chrome. I've replaced pull-right with form-control and the Invite button now works consistently. I'm not sure what a more elegant fix would be but wanted you to be aware. 

```
        <div class="row">
                <div class="col-lg-6">
                <!-- IMPORT partials/users_list_menu.tpl -->
                </div>
                <div class="col-lg-3">
                        <!-- IF inviteOnly -->
                        <!-- IF loggedIn -->
                        <!-- <button component="user/invite" class="btn btn-success pull-right"><i class="fa fa-users"></i>[[users:invite]]</button> -->
                        <button component="user/invite" class="btn btn-success form-control"><i class="fa fa-users"></i>[[users:invite]]</button>
                        <!-- ENDIF loggedIn -->
                        <!-- ENDIF inviteOnly -->
                </div>

```

**Comment by julianlam** [comment]
Thanks, that's quite a peculiar bug affecting a portion of NodeBB that is disabled by default, so let's see what the problem is...
