### ISSUE TITLE
Chats broken

### ISSUE THREAD

**Issue by pitaj** [NodeBB/nodebb-theme-persona#331]
![screenshot_20161102-093152](https://cloud.githubusercontent.com/assets/803701/19935572/2311a6fc-a0e0-11e6-9969-867df5f9d60a.png)

Also, chat shouldn't show both the user icon as the chat icon and the user icon below it there's only one other participant.

**Comment by pitaj** [comment]
@psychobunny

**Comment by KitsuneSolar** [comment]
![2016-11-05 15-39-49](https://cloud.githubusercontent.com/assets/12877339/20030066/322d1ffa-a36e-11e6-9961-d471e08c53d6.png)
