### ISSUE TITLE
Roboto font without latin-extended

### ISSUE THREAD

**Issue by sznowicki** [NodeBB/nodebb-theme-persona#337]
Hello there

For some languages, Roboto font is missing some symbols (e.x. ąęćżź). Normally for some languages, Roboto should be extended with latin-extended pool of symbols. Otherwise it falls back to Helvetica Neue (which is quite OK) or Arial (which is quite bad). 

Can we (I can prepare it) adjust the .less file so it will add the extension if language is within those "latin-extended" pool?

I could also fix this problem forking the repository but I guess it's better to fix it globally.

However, I don't know if there's an option to get this information on build stage. If you could help me getting into the project I'd be glad to contribute.

**Comment by psychobunny** [comment]
@sznowicki happy to accept a PR if you're able to do it :)

**Comment by MegaGM** [comment]
Cyrillic Extended
Latin Extended
Greek Extended
Vietnamese

Please :smiling_imp:

**Comment by sznowicki** [comment]
I already did it in my forked repo (also available in npm: nodebb-theme-persona-latin-extended).

Since we are using it on production I'll be syncing the repo with original one every time new major will be released). 

Maybe it's better idea, than adding support for the markets it's not required.

@MegaGM - please check if nodebb-theme-persona-latin-extended suits your needs, if not I'll be happy to extend the fonts with additional charsets.

**Comment by psychobunny** [comment]
@pichalite brought up a good point in internal discussion, it's probably better to just do this import via the Custom CSS tab in the ACP if you really need it. That said, if people want to use your package instead that also works - I'm going to close this then. Thanks :)

**Comment by pichalite** [comment]
@sznowicki It's way easier if you add the font import to "Custom CSS" section in ACP instead of maintaining a repo just for that.

**Comment by sznowicki** [comment]
After some time forking this theme and using it in our Polish forum I must say it's quite a pain for a long term maintenance.

If you're still happy to accept my pull request with extended Roboto url, I'd be more than happy preparing it and deprecating my npm package (nodebb-theme-persona-latin-extended).

as @MegaGM  pointed out, there might be users with additional needs in the future and extending Google Web Fonts with all possible subsets is not good way to go. My opinion on this is either a general use theme should support different locales (as nodebb does) or it might be a good idea to not include Roboto in the bundle at all.

This way, Android users would get Roboto, others - other platform native fonts (Helvetica Neue / Arial). It require some additional effort with styling since those Roboto is not "compatible" with Helvetica (Neue) and Arial, but I think it's possible.

I'm looking forward hearing from you. All  the best!
