### ISSUE TITLE
Chats with defined titles load the wrong user's avatar

### ISSUE THREAD

**Issue by BenLubar** [NodeBB/nodebb-theme-persona#340]
Due to this line: https://github.com/NodeBB/nodebb-theme-persona/blob/a8a2787d5d21a7dd233704fcf141fcd62850d2bf/lib/persona.js#L66

**Comment by barisusakli** [comment]
seems like already fixed here https://github.com/NodeBB/nodebb-theme-persona/commit/2b66f7cfccfeb7578b1ebdd6955464a29517566b
