### ISSUE TITLE
permalink copy URL

### ISSUE THREAD

**Issue by frissdiegurke** [NodeBB/nodebb-theme-persona#35]
Once upon a time there was an input-field below the permalinks of each post. I can neither find it within persona nor within lavender source anymore.
I'd love to see this again since the URL gets changed and your chance to read the URL of a specific post from the URL is small.

Any chance to get this or sth. alike back?

**Comment by julianlam** [comment]
Is this necessary anymore, as the url dynamically updates as you browse the
topic?

**Comment by frissdiegurke** [comment]
Since you get the URL of the post on the very top of your window **yes**.

You can't get the ones on the bottom of your screen if you don't resize/zoom your viewport.

Additionally as a newbee you don't know that the URL contains the most-top post you see.
Hence you'd associate the link with the exact post you'd expect to find it somewhere close.

**Comment by julianlam** [comment]
Yes, I will admit that this is less than clear... so I'd support a link to retrieve the permalink for this reason. 

Perhaps also an indicator on the left side that shows which post you're *reading*... but that may be overreaching :laughing:
