### ISSUE TITLE
Fade-out color not compatible with current skin

### ISSUE THREAD

**Issue by RoiEXLab** [NodeBB/nodebb-theme-persona#353]
[The fade-out html class](https://github.com/NodeBB/nodebb-theme-persona/blob/4aa302b4511475ad32b8f68cb11eb06dc16aeac0/less/style.less#L152-L156) is used by the essential widgets plugin to "highlight" the overflow of a specific post.
The problem with this is, that it won't adapt to the current selected skin.
It's always a "transparent to white" fade, although it should be "transparent to background color"

**Comment by pitaj** [comment]
Unfortunately I don't this this is possible to fix.

**Comment by barisusakli** [comment]
Maybe possible if we add a fade-out class for each skin 😆

**Comment by RoiEXLab** [comment]
@barisusakli Good idea... replace `.fade-out` with `.skinName .fade-out` correct?

**Comment by barisusakli** [comment]
Yes and need one for `.skin-default .fade-out` which is the current `.fade-out`

**Comment by RoiEXLab** [comment]
I'll see if I can create a PR for this in a couple hors...

**Comment by RoiEXLab** [comment]
@barisusakli Hmm... I found an issue with this...
The class is set by the user, meaning `.skin-default` can be everything, dependend on what is set by the server owner...
Related to https://github.com/NodeBB/NodeBB/issues/5497

**Comment by barisusakli** [comment]
I thought `.skin-default` meant no bootswatch skin selected, @psychobunny or @pichalite can probably confirm.

**Comment by RoiEXLab** [comment]
Would make sense, but isn't the case

**Comment by pichalite** [comment]
@barisusakli nah... `.skin-default` means skin is set to `Default` at user level. If a skin is set from the ACP... it will still be `.skin-default` if the user level setting is set to `Default`.

**Comment by barisusakli** [comment]
Ok so, if the admin sets the skin to `darkly` and the user sets their skin to `default` the body class gets `skin-default` instead of `skin-darkly`?

**Comment by RoiEXLab** [comment]
Correct

**Comment by RoiEXLab** [comment]
@barisusakli opened #354

**Comment by barisusakli** [comment]
https://github.com/NodeBB/nodebb-theme-persona/pull/354
