### ISSUE TITLE
notifications/list problem

### ISSUE THREAD

**Issue by ornithes** [NodeBB/nodebb-theme-persona#356]
![image](https://cloud.githubusercontent.com/assets/15672497/24719552/d29a10c4-1a42-11e7-8bc3-6b55c5861505.png)

It is blue :/

**Comment by pichalite** [comment]
@pikshub I don't see what the problem is here. The items in the notification list are blue for that skin. How is that a problem?

**Comment by pikshub** [comment]
@pichalite This is the default skin. Only the header color has been changed. The default skin color is gray. But it was blue after we updated.

**Comment by pichalite** [comment]
what's your NodeBB version?

**Comment by pikshub** [comment]
@pichalite master. https://github.com/NodeBB/NodeBB/commit/bb0ec540bd9351098d8c52d94d05e793ddd9eece

**Comment by pikshub** [comment]
When you change the language the problem is solved. It breaks down in Turkish

**Comment by barisusakli** [comment]
This is on purpose I believe so that the text is visible on all skins, https://github.com/NodeBB/nodebb-theme-persona/commit/353fe81abbd452ba4774f9a0f2ee601b1f19a4ce

If we set a color then the links might be unreadable on some skins
