### ISSUE TITLE
When update to 1.4.6,Recent Card plugin lead somthing broken.

### ISSUE THREAD

**Issue by a632079** [NodeBB/nodebb-theme-persona#358]
* NodeBB v1.4.5 -> 1.4.6
* Recent Card Plugin v0.3.1
After I updated my community,I found I can't delete posts successfully.In this post,  I know this is a problem  in recent card.
(You can delete the post,but you can't clean these deleted post.it would report "The post has deleted")
cloud you fix it as soon as possible?
Thank you.

**Comment by julianlam** [comment]
Shouldn't have anything related to recent cards... what error do you see in server or client when deleting posts?

**Comment by a632079** [comment]
@julianlam 
Sorry, i can't see any error in server or client.
But this error is very easy to reappear.
1. Use NodeBB v1.4.5
2. Enable Recent Card v0.3.1
3. Update to NodeBB v1.4.6
4. After  that,Try to delete a post or a topic.
5. Try to clean the post(it may throw can't connect the server).
6. refresh the page,then you will find the post is exist yet.
7. Try again,it will throw a error like"This topic has deleted 此贴已被删除"
8.Refresh again,it is exist yet.
9.check server log and brower's log ,find nothing throwed.
This is a bad  way to solve this problem: https://community.nodebb.org/topic/9507/nodebb-plugin-featured-topics-extended-feature-topics-in-a-news-blog-page-and-widgets/26
