### ISSUE TITLE
sidebar icons are not aligned

### ISSUE THREAD

**Issue by Alisummer** [NodeBB/nodebb-theme-persona#360]
![screenshot_20170520-114257](https://cloud.githubusercontent.com/assets/7764726/26272709/c0afc7f4-3ce4-11e7-83f8-d1f5f2664eba.png)

**Comment by barisusakli** [comment]
They all use fa-fw, 
![image](https://user-images.githubusercontent.com/2583394/46777784-c5e93080-ccde-11e8-87c7-4219e3629fb5.png)

**Comment by Alisummer** [comment]
![screenshot_20181011-120052](https://user-images.githubusercontent.com/7764726/46780064-5fe7c200-cd4d-11e8-8e91-d509366ade0b.png)
Official forum is not aligned also.

**Comment by barisusakli** [comment]
Fixed login and register as well
