### ISSUE TITLE
Improper alignment 

### ISSUE THREAD

**Issue by LindaBadurina** [NodeBB/nodebb-theme-persona#371]
<img width="555" alt="screen shot 2017-08-17 at 1 20 51 pm" src="https://user-images.githubusercontent.com/14350540/29425065-ea62eb42-834f-11e7-9d66-c5b87437d2d8.png">

Lines were drawn to show how far from being lined up with each component (icon, category title, and topics/posts) this entire thing is. "Announcements" should be moved down and "topics/posts" up to align it with the icon

**Comment by LindaBadurina** [comment]
![fixedalignment](https://user-images.githubusercontent.com/14350540/34740309-f4eefd66-f54c-11e7-9bb8-aea8da8b53fe.jpg)

Fixed

**Comment by julianlam** [comment]
@LindaBadurina Was this fix committed to the theme? Can you link it here?

**Comment by julianlam** [comment]
Nevermind, found it: https://github.com/NodeBB/nodebb-theme-persona/pull/399

**Comment by julianlam** [comment]
Merged prematurely... re-open PR when ready, thanks.
