### ISSUE TITLE
Unnecessarily huge search bar is touching the buttons above it in Home/Users

### ISSUE THREAD

**Issue by LindaBadurina** [NodeBB/nodebb-theme-persona#375]
<img width="975" alt="screen shot 2017-08-17 at 2 57 32 pm" src="https://user-images.githubusercontent.com/14350540/29428788-740dd094-835c-11e7-8eec-086c8baa8b34.png">

There's no reason for this search bar to be taking up this much space. It should also be moved so that it isn't touching the buttons above it. Moving it / fitting it in to be in the same row as these items would be the most logical solution

**Comment by barisusakli** [comment]
Already fixed I believe
