### ISSUE TITLE
Post Scroll Bar does ignore widgets in the footer

### ISSUE THREAD

**Issue by RoiEXLab** [NodeBB/nodebb-theme-persona#377]
If you put something in the widget are like a Donation widget, the widget is ignored when the scrollbar is displayed on the screen.
![Screenshot](https://user-images.githubusercontent.com/8350879/30178850-bf04768e-940a-11e7-8c47-853a18c306e4.png)

**Comment by pitaj** [comment]
So you mean that the pagination overlay is over the widget? That there isn't enough padding on the bottom?

What do you expect it to look like?

**Comment by RoiEXLab** [comment]
@pitaj Correct. There's not enough padding.
I'd expect it to not overlap the footer widgets.

I haven't looked into the details, but I assume only the div cointaining the page contents, e.g. posts has padding on the bottom which is not sufficient if the footer is not empty.
I'm not sure if this is easily fixable, but I'd be happy to at least see a possible workaround. 

My example does contain 2 divs, the ones provided by PayPal for donation widgets, I could try to reproduce this issue by using a simple image or post the html if that helps.
