### ISSUE TITLE
Post voting is broken

### ISSUE THREAD

**Issue by orweinberger** [NodeBB/nodebb-theme-persona#379]
I'm running the latest 6.1.1 version (this was also the case in 6.1.0, not sure about versions prior to that), whenever I try to upvote or downvote a post, I get the voters summary dialog and can't actually vote. Another smaller issue is that the content shifts a bit whenever that dialog pops up.

Here's a gif showing the issue

![awesomescreenshot-2017-10-08t13-02-08-635z](https://user-images.githubusercontent.com/1876045/31317073-eac06f1c-ac42-11e7-9b38-c964612d4b75.gif)

**Comment by julianlam** [comment]
You are not able to upvote your own post.

**Comment by orweinberger** [comment]
Oh, that makes sense. It might be a good idea to alter the behavior and display a message saying 'You cannot vote for your own post' or something similar.

**Comment by julianlam** [comment]
:point_up:
