### ISSUE TITLE
Small visual issue (only reproducible in the mobile version of NodeBB)

### ISSUE THREAD

**Issue by kenygamer** [NodeBB/nodebb-theme-persona#381]
https://m.imgur.com/a/mUoYL

As you may see, there's no spacing between the alert box and the New Topic button. This is a *minimal* error and it is reproducible in the latest NodeBB version (I'm up to date).

Linux Ubuntu 16.04.3 LTS
8 GB RAM • 8 Cores / 4 Threads • 240 GB SSD • 2.1 GHz

**Comment by kenygamer** [comment]
How to apply changes

**Comment by barisusakli** [comment]
https://github.com/NodeBB/nodebb-theme-persona/commit/2dd3a3e251e9aa5fa0c8c4e2871190ae8a70e87c#diff-b2d5dbbac0a14c90415afe088651032a

**Comment by kenygamer** [comment]
Do I have to upgrade NodeBB to apply changes how?

**Comment by barisusakli** [comment]
Yes, upgrade to nodebb 1.7.0

**Comment by kenygamer** [comment]
Thanks
Would you mind  in taking a look to this [forum thread](https://community.nodebb.org/topic/11538/php-code-to-node-js-code-conversion) and help me?
Thank you again

**Comment by kenygamer** [comment]
Unread topics when none it also has the alert box small issue..
