### ISSUE TITLE
Some words or not right-to-left aligned

### ISSUE THREAD

**Issue by mohammadhassan99** [NodeBB/nodebb-theme-persona#388]
- **NodeBB version:** 1.7.0
- **NodeBB git hash:** dbdc05404daeac7021b60f22f7c18588ca126cfd
- **Database type:** mongo
- **Database version:** 3.2.11

Hi, as you can see below, some words are not right-to-left aligned. Our forum uses fa-IR language.

![photo5828183523486444744](https://user-images.githubusercontent.com/31972226/33296316-1f859e28-d3f0-11e7-9e0e-4fd865661919.jpg)

**Comment by julianlam** [comment]
Hello @mohammadhassan99 -- is it just the menu items in the sidebar?

**Comment by mohammadhassan99** [comment]
@julianlam Until now, I can yes. And also it happens for chat sidebar too.

**Comment by julianlam** [comment]
v7.2.4
