### ISSUE TITLE
Some parts can't be read

### ISSUE THREAD

**Issue by mohammadhassan99** [NodeBB/nodebb-theme-persona#390]
Hi in **Yeti** skin some parts can't be read unless you hover mouse cursor over that part.
For example, the word **"log out"** and chats have this problem. 
Don't you think it needs to be fixed ? 🤔 

![picture 1](https://user-images.githubusercontent.com/31972226/33445864-790eb112-d613-11e7-80c0-4340ec7b20b5.png)

![picture 2](https://user-images.githubusercontent.com/31972226/33445820-4fd0d690-d613-11e7-8728-b094a9ee13c8.png)

**Comment by julianlam** [comment]
Unfortunately not, as these styling issues are not really fixable due to the way Bootstrap is loaded. It is very likely that skins will be removed in a future version of NodeBB.
