### ISSUE TITLE
why I can't see side bar when i click this icon

### ISSUE THREAD

**Issue by thinkin** [NodeBB/nodebb-theme-persona#394]
![image](https://user-images.githubusercontent.com/18477667/34319096-edaa2382-e813-11e7-89b8-d6061024092d.png)

**Comment by pitaj** [comment]
Are there any errors in the console? Is the page completely loaded?

**Comment by Starystars67** [comment]
Hi, I'm getting the same issue in that the sidebar fails to open on mobile when clicking the ladder/menu button. As for errors I'll get back to you shortly

**Comment by Starystars67** [comment]
Further to my last comment there are no errors in the console

**Comment by pitaj** [comment]
Have you tried Firefox? What version of NodeBB and persona?

**Comment by Starystars67** [comment]
Negative on Firefox as I'm on mobile as for versions latest on both

**Comment by psychobunny** [comment]
Does it work for you on our community site? https://community.nodebb.org

**Comment by Starystars67** [comment]
Yes the menu works fine on your site

**Comment by Starystars67** [comment]
A rebuild has not resolved the issue unfortunately, the menu in the ACP works just fine though

**Comment by Starystars67** [comment]
Both are latest update just a couple days ago, nodebb is 8.2.1 persona not sure off the top of my head but unless you released one in the last 2 days I have latest

**Comment by pitaj** [comment]
Post the output of `npm ls pulling`

**Comment by Starystars67** [comment]
hello, thank you for your reply and the delay in mine.
Here is the output of `npm ls pulling`

`-- nodebb-theme-persona@8.0.9`
  `-- pulling@1.1.2`

**Comment by Starystars67** [comment]
Currently updating and building to see if the issue was resolved in an update that i missed

**Comment by pitaj** [comment]
Can you try it on Firefox? You say there are no errors in console, can you double-check? You are using the persona theme, right?

**Comment by Starystars67** [comment]
just downloaded Firefox on my mobile and it has the same issue, I have also attached a copy of console after loading the web page in chrome on PC using mobile view and then clicking on the button to open it but with no luck:
![image](https://user-images.githubusercontent.com/15389482/39401915-3f36ab10-4b49-11e8-8218-7fbcaadfede5.png)

**Comment by pitaj** [comment]
Are you using the Persona theme or not?

**Comment by Starystars67** [comment]
Yes I am using Persona theme

**Comment by Starystars67** [comment]
Hi, I have just tried the latest nodebb update (v1.9.2) and the issue still persists however I have noticed the same issue isn't there for the ACP. Don't know if this helps at all?

**Comment by pitaj** [comment]
I looked at your site, and I couldn't figure out what was wrong. Have you tried disabling all plugins, rebuilding, and restarting?

**Comment by Starystars67** [comment]
Hello, I have just disabled all plugins except the default ones and the issue still persists. any other ideas or advice? Could you tell me which JS file is being used when i click on the button so that i can look into debugging it my self?

**Comment by Starystars67** [comment]
@pitaj Did you also have the error when using my site?

**Comment by Starystars67** [comment]
Hello @pitaj , I have just disabled `nodebb-plugin-mega-colors` and rebuilt and restarted and it has not resolved the matter which is the same result as when I disabled all my plugins (except default I.E Markdown) and this does not solve it, if you can help advise me as to where the control for the sidebar on mobile view is (where and what JS file) then i can look into debugging it and maybe find a fix my self to help you out a bit.

Kind Regards,

Mitch D

**Comment by pitaj** [comment]
The relevant files are:

- https://github.com/NodeBB/nodebb-theme-persona/blob/master/lib/persona.js#L121-L288
- And the pulling library: https://github.com/NodeBB/pulling

**Comment by julianlam** [comment]
Closed as this seems to be a plugin interfering with sidebar
