### ISSUE TITLE
I cannot see the number of recent and unread topics 

### ISSUE THREAD

**Issue by mohammadhassan99** [NodeBB/nodebb-theme-persona#395]
NodeBB version: 1.7.3

Hi, I can't see the number of recent and unread topics in mobile themes.

![2017-12-30_102714](https://user-images.githubusercontent.com/31972226/34452080-bea72fec-ed4c-11e7-803d-6f9ac5ca8ef9.png)

**Comment by pitaj** [comment]
https://github.com/NodeBB/nodebb-theme-persona/commit/76279f7f8ea98a81fcd0ee9f6fe1efee775acb68

This is already fixed to be released soon
