### ISSUE TITLE
Navbar goes to the next line at certain widths (after adding custom nav links)

### ISSUE THREAD

**Issue by dangerusslee** [NodeBB/nodebb-theme-persona#402]
On my site, from width 1022px to 844px the navbar drops down to the next line and obsures the title.  

We have the seach plugin and a custom nav icon for tags.  

![image](https://user-images.githubusercontent.com/24903887/35160723-03cb91de-fd0c-11e7-859b-646bb6b7a647.png)

**Comment by pitaj** [comment]
This is because there are too many links in the navbar. You could either reduce those, or change your theme to include a drop-down menu or something. 

We could possible allow them to scroll horizontally instead of overflowing like this.

**Comment by paviro** [comment]
I am having the same issue. Wouldn't it be possible to just push the content down a bit so the statusbar does not overlap? I would really like to add some text to the icons which is basically impossible even if you add way less icons than I did.
![persona](https://user-images.githubusercontent.com/992826/39726244-c0e6ed3a-524e-11e8-942c-5b4f377b98bc.png)
