### ISSUE TITLE
Slash (/) missing between category and subcategory under a certain width

### ISSUE THREAD

**Issue by dangerusslee** [NodeBB/nodebb-theme-persona#403]
Under 1090px 
![image](https://user-images.githubusercontent.com/24903887/35160829-565f7776-fd0c-11e7-970b-ca09a39e3c32.png)

Over 1090px
![image](https://user-images.githubusercontent.com/24903887/35160860-6b593ac2-fd0c-11e7-961f-fb2f9462ac4b.png)

**Comment by julianlam** [comment]
Unfortunately this looks to be a bug with Bootswatch as it does not reproduce on Persona with no skin.

**Comment by dangerusslee** [comment]
How do you suggest we solve this?
