### ISSUE TITLE
html tags showing in display 

### ISSUE THREAD

**Issue by alihasana** [NodeBB/nodebb-theme-persona#406]
hi team,

html tags showing in display,

let me know how tto solve this error

thanks

![image](https://user-images.githubusercontent.com/32835040/35576269-d74bd3a4-05de-11e8-8400-6bb30a5a045c.png)

**Comment by barisusakli** [comment]
Is markdown plugin activated? What is the raw content of those posts? Does it happen on latest nodebb?
