### ISSUE TITLE
Nodebb utils.addCommasToNumbers breaks Most Flagged href with large Uids

### ISSUE THREAD

**Issue by uplift** [NodeBB/nodebb-theme-persona#410]
Hi,

When user uids enter the thousands a comma is added to the href link which breaks the link. The link still functions but the flags page shows no flags with the comma.

I tracked this down to utils.addCommasToNumbers in nodebb being run on elements with class of .formatted-number as this function gets the elements html and therefore the child A element and does the replace on the href as well as any other numbers greater than a thousand.

Locally I moved the class to the A element to get it to work completely but not sure if that is the optimal solution.

https://github.com/NodeBB/nodebb-theme-persona/blob/7e36f48dac5a2f7b3b589da4797f7cc409ac82d3/templates/partials/users_list.tpl#L41

**Comment by julianlam** [comment]
@uplift Ha! that's kind of amusing, isn't it :smile: 

Looks like the `adCommasToNumbers` function is a little too zealous in converting numbers with more than four digits, I'll take a look at the `utils` method itself to see what can be done.

**Comment by barisusakli** [comment]
Yeah `.formatted-number` class should be on the direct parent that has the number.
