### ISSUE TITLE
White background behind navigation

### ISSUE THREAD

**Issue by xpowert** [NodeBB/nodebb-theme-persona#411]
Hello i am helping out my friend who have a NodeBB forum - version 0.7.1 and use Persona theme. 
He told me that  white background appear and he cant get rid of it. 

This is how the problem looks, maybe someone can tell me where is the problem and how to fix it ? 

Link to image  -> https://i.imgur.com/lqtniiV.png

**Comment by barisusakli** [comment]
Make sure to update to a more recent of nodebb, this problem is likely resolved. If you want to apply the changes without upgrading see this PR https://github.com/NodeBB/NodeBB/pull/6304
