### ISSUE TITLE
Disable side panels while zooming

### ISSUE THREAD

**Issue by exomarty** [NodeBB/nodebb-theme-persona#414]
When you zoom on mobile in a thread, and move to the left or right of the page , the left menu and chats panel appears and hide all text
Same happens when you try to drag recents topics squares on nodebb community frontpage and chats panel shows

Thank you

**Comment by julianlam** [comment]
Thoughts on this, @pitaj ?

**Comment by pitaj** [comment]
The recent topics thing I can confirm... Not sure what changed there.

**Comment by exomarty** [comment]
Guys nodebb is great and  you do awesome stuff with the engine but then forger about this kind of things that kill user experience
This bug happens on many places 
![c9e5773f-7049-41b9-b680-c7f7e4dc2617](https://user-images.githubusercontent.com/10746278/44881749-0356a900-acb1-11e8-8d4e-9a378c580c45.gif)

**Comment by pitaj** [comment]
Yeah somehow the ignores are broken, I'll have to look and see

**Comment by pitaj** [comment]
I'm not able to reproduce the slideout when zooming. My code specifically ignores when multiple touches are on the screen. My latest change ignores any touch events from horizontally scrollable elements.
