### ISSUE TITLE
Ability to turn on night mode for Node BB

### ISSUE THREAD

**Issue by FaizanZahid** [NodeBB/nodebb-theme-persona#417]
Our users have requested that all many sites offer this, do we already have a thing called night mode in Node bb persona theme?

It is usually used on devices to reduce eye strain. We can have the night mode on YouTube, Twitter etc

**Comment by psychobunny** [comment]
Hi @FaizanZahid, check this plugin out made just for Persona:
https://github.com/psychobunny/nodebb-plugin-night-mode

**Comment by FaizanZahid** [comment]
Thanks, i tried to find this plugin on my ACP but couldn't find it. Is there any special way to install theme plugins?
