### ISSUE TITLE
Untranslatable string

### ISSUE THREAD

**Issue by Dravere** [NodeBB/nodebb-theme-persona#418]
There is a string that can't be translated into other languages: https://github.com/NodeBB/nodebb-theme-persona/blob/dee209d4941bb997f74795031f89fe38985e3766/lib/persona.js#L271

Would be nice to get a possibility to translate that string. Also it doesn't make much sense to display that option for desktop users.

**Comment by barisusakli** [comment]
@Dravere please open a PR if you want to contribute translations for that string
