### ISSUE TITLE
Real-time & emoji-extended

### ISSUE THREAD

**Issue by nhlpl** [NodeBB/nodebb-theme-persona#42]
I have been watching a thread 4148 and author (J3nkl3r) updated first post.
https://community.nodebb.org/topic/4148/can-we-fix-a-country-forum-with-subforums-for-wanted-languages

Added content was:
<img class="emoji emoji-extended" src="https://community.nodebb.org/plugins/nodebb-plugin-emoji-extended/images/wink.png" title=";)" alt=";)">

Possible bug:
";)" as an image has been displayed in wrong width. I think near to all available blank space. Not 20 px per 20 px but more like 20 x 200 px. 

Browser: Opera beta 28.0.1750.36.

After hitting F5 it works as it should and ";)" emoji symbol is displayed correctly.

**Comment by psychobunny** [comment]
known bug actually, I'm waiting for: https://github.com/julianlam/nodebb-plugin-markdown/issues/34
