### ISSUE TITLE
Consecutive chat messages are not editable

### ISSUE THREAD

**Issue by julianlam** [NodeBB/nodebb-theme-persona#442]
![](https://user-images.githubusercontent.com/923011/47386310-50b42d00-d6da-11e8-9352-79d843420fd2.png)

:point_up: design for the fix @LindaBadurina

**Comment by pitaj** [comment]
Fixed, looks like this
![image](https://user-images.githubusercontent.com/803701/52160419-5672c480-2672-11e9-8a2b-99d6f2951681.png)
