### ISSUE TITLE
Chat collapsing is too greedy

### ISSUE THREAD

**Issue by julianlam** [NodeBB/nodebb-theme-persona#444]
![selection_617](https://user-images.githubusercontent.com/923011/49811682-be232800-fd31-11e8-89bf-61778df4e975.png)

The most recent message was posted half a year after the previous message. They should not be collapsed together.

**Comment by barisusakli** [comment]
https://github.com/NodeBB/NodeBB/commit/fe0f95a2b11a82252778a25aced879d2e4f939b5
