### ISSUE TITLE
Post appears between categories on main page 

### ISSUE THREAD

**Issue by tom-rade** [NodeBB/nodebb-theme-persona#446]
- **NodeBB version:** 1.11.0
- **NodeBB git hash:** 26ccd8f626f7296138ab1c0575c0b49c7dda91fb
- **Database type:** mongo
- **Database version:** v4.0.4

- **Exact steps to cause this issue:**

	1. Visit the homepage with the category overview
	2. Let someone else create a post
        3. The post of someone else appears between categories

This is how it looks like (Desktop has the same problem): https://imgur.com/a/zlbUAmt

- **What you expected:**

I expected this not to happen.

- **What happened instead:**

The post appears between the categories on the homepage

**Comment by julianlam** [comment]
Sadly the image you posted does not work and is 404 when pasted into browser.

Can you reproduce this on community.nodebb.org?

**Comment by tom-rade** [comment]
@julianlam The link is now fixed. I'll test this in a second with community.nodebb.org.

**Comment by tom-rade** [comment]
@julianlam Not reproducable on community.nodebb.org for some reason. Even with disabled custom CSS this occurs:

https://i.imgur.com/owOXZPD.png This is the HTML-Preview on my forum.

Installed plugins:

```
	 - nodebb-theme-persona
	 - nodebb-plugin-markdown
	 - nodebb-plugin-mentions
	 - nodebb-widget-essentials
	 - nodebb-rewards-essentials
	 - nodebb-plugin-soundpack-default
	 - nodebb-plugin-emoji
	 - nodebb-plugin-emoji-android
	 - nodebb-plugin-dbsearch
	 - nodebb-plugin-recent-cards
	 - nodebb-plugin-newsletter
	 - nodebb-plugin-composer-default
	 - nodebb-plugin-poll
	 - nodebb-plugin-imgur
	 - nodebb-plugin-custom-pages
	 - nodebb-plugin-math-captcha
	 - nodebb-plugin-pwned-passwords
	 - nodebb-plugin-2factor
	 - nodebb-plugin-reputation-rules
	 - nodebb-widget-board-stats
	 - nodebb-plugin-spam-be-gone
```

**Comment by tom-rade** [comment]
@julianlam I found it! Not reproducable on community.nodebb.org because you've enabled default settings. If you set to hide-last-entry to true, then this thing happens.

**Comment by tom-rade** [comment]
@julianlam Now I've got it: Not reproducable on community.nodebb.org because you've enabled default settings. If you set to hide-last-entry to true, then this thing happens.
