### ISSUE TITLE
Broken implementation of "Hide last post on categories view"

### ISSUE THREAD

**Issue by tom-rade** [NodeBB/nodebb-theme-persona#448]
- **NodeBB version:** v1.11.1
- **NodeBB git hash:** 90b4d40e77141ed203494e5cb5f31b8a0209b7bf
- **Database type:** mongo
- **Database version:** v4.0.5

- **Exact steps to cause this issue:**

	1. Go to /admin/plugins/persona (the Persona Theme settings)
	2. Set "Hide last post on categories view" to true
	3. Visit the homepage with the category overview
	4. Let someone else (a different account) create a post
        5. The post content of someone else (a different account) appears between categories on the category overview

This is how it looks like (Affects desktop too): https://imgur.com/a/zlbUAmt

- **What you expected:**

I expected no live addition of new posts between categories with broken CSS.

- **What happened instead:**

The post appears between the categories on the homepage which does not look good.

**Comment by barisusakli** [comment]
https://github.com/NodeBB/NodeBB/issues/7432
