### ISSUE TITLE
RTL with dropdown menus

### ISSUE THREAD

**Issue by PostMidnight** [NodeBB/nodebb-theme-persona#455]
Hi, 

It seems that the dropdown menus could use the following minor improvement, so they will stick inside the screen:

```
html[data-dir=rtl] .pull-right {
	.dropdown-menu-right,
	.dropdown-menu {
		right: auto;
		left: 0;
		float: left;
		text-align: right;
	}
}

```

**Comment by barisusakli** [comment]
Please let us know if this is happening on https://community.nodebb.org/ and share a screenshot
