### ISSUE TITLE
Mobile side menu does not work on iOS (safari or chrome)

### ISSUE THREAD

**Issue by pichalite** [NodeBB/nodebb-theme-persona#46]
Mobile side menu does not work on iOS (safari or chrome). Does not open at all.

**Comment by julianlam** [comment]
Yeah, I reproduced this on an iPhone recently...

**Comment by kurdin** [comment]
It never worked on mobile devices.

**Comment by barisusakli** [comment]
>It never worked on mobile devices

Works fine on nexus 5 chrome

![image](https://cloud.githubusercontent.com/assets/2583394/7417900/7cf989f2-ef37-11e4-93f7-8d4e59da410e.png)

**Comment by pichalite** [comment]
:+1:
