### ISSUE TITLE
Users icon don't appear in the navigation menu

### ISSUE THREAD

**Issue by zipang** [NodeBB/nodebb-theme-persona#460]
My theme is a fork of nodebb-theme-persona and is located here : https://github.com/zipang/nodebb-theme-mathforu

After an upgrade to nodebb v1.11, i've noticed that my navigation icon to access the users pages doesn't appear anymore in the top bar, although it is configured to be visible in the administration.
![nodebb-navigation-menu](https://user-images.githubusercontent.com/658082/52524323-0b713680-2c9c-11e9-84a0-df689bc00dae.png)
![nodebb-navigation-configuration](https://user-images.githubusercontent.com/658082/52524376-96523100-2c9c-11e9-8f54-e153bc9a2a3f.png)

My belief is that this section is generated inside templates/partials/menu.tpl
and specifically in this section : 

```html
<ul id="main-nav" class="nav navbar-nav">
	<!-- BEGIN navigation -->
	<!-- IF function.displayMenuItem, @index -->
	<li class="{navigation.class}">
		<a class="navigation-link" href="{navigation.route}" title="{navigation.title}" <!-- IF navigation.id -->id="{navigation.id}"<!-- ENDIF navigation.id --><!-- IF navigation.properties.targetBlank --> target="_blank"<!-- ENDIF navigation.properties.targetBlank -->>
			<!-- IF navigation.iconClass -->
			<i class="fa fa-fw {navigation.iconClass}" data-content="{navigation.content}"></i>
			<!-- ENDIF navigation.iconClass -->

			<!-- IF navigation.text -->
			<span class="{navigation.textClass}">{navigation.text}</span>
			<!-- ENDIF navigation.text -->
		</a>
	</li>
	<!-- ENDIF function.displayMenuItem -->
	<!-- END navigation -->
</ul>
```

I have merged the latest version of nodebb-theme-persona and i share the same code on this section.

What could have happened ?

**Comment by barisusakli** [comment]
Do you have Global Moderators selected? If so it will only show up for global moderators. Try deselecting all groups and saving.

**Comment by zipang** [comment]
Thank you @barisusakli !
That solved my problem ! 
But the fact is that the way selecting groups in this pannel works is really unclear. 
I believed that all groups appearing in the list had the privileges..
You should add a checkbox in this list to _clearly indicate_ which groups have the navigation icon and which don't have it.
Even worse is the fact that "Administrators" or "Global Moderators" all belong to "registered users" don't they ? So what is the meaning to allow the navigation item for "registered users" and not for "Global Moderators" ???
And every modification should be immediate without having to use the Save icon.

**Comment by pitaj** [comment]
There's no an easy way to style those. We could put something like "select the groups you want to see the widget"
