### ISSUE TITLE
Brand logo

### ISSUE THREAD

**Issue by youhosi** [NodeBB/nodebb-theme-persona#463]
This function not working
- `{brand:logo:display}`

https://github.com/NodeBB/nodebb-theme-persona/blob/d7d4a7fc1b3526219ee92179e11851a7a170a172/templates/partials/menu.tpl#L13

**Comment by pitaj** [comment]
Please describe how it isn't working. What do you expect? What is actually happening?

**Comment by youhosi** [comment]
All in all, this question should be what this function is for and what it returns.
