### ISSUE TITLE
Sidebar appears while scrolling recent topics banner

### ISSUE THREAD

**Issue by exomarty** [NodeBB/nodebb-theme-persona#464]
known issue long time ago
If you swipe right or left on recent topics banner of the homepage like community.nodebb.org has ... , the chat right bar or the left menu sidebar will appear and disturb you

Tested iphone 8 safari amd chorme latest ios version

**Comment by pitaj** [comment]
Not sure why this isn't working, I'll have to look into it.

**Comment by pitaj** [comment]
Fixed in NodeBB-Community/nodebb-plugin-recent-cards@b50fc802d53c81bd0e07cf693175326e3fe55754
