### ISSUE TITLE
New Topic, Reply aren't working with activated Persona Theme

### ISSUE THREAD

**Issue by deckardstp** [NodeBB/nodebb-theme-persona#47]
Hi,
as soon as I activate the theme I'm no more able to raise new topics or reply to my existing. Editing is also not possible. My log tells me:

4/4 09:38 [6708] - [33mwarn[39m: [plugins.reload] Library not found for plugin: nodebb-theme-persona
4/4 09:38 [6708] - [33mwarn[39m: [meta/templates] Partial not loaded: partials/requirejs-config.tpl
4/4 09:38 [6708] - [33mwarn[39m: [meta/templates] Partial not loaded: partials/data/category.tpl
4/4 09:38 [6708] - [33mwarn[39m: [meta/templates] Partial not loaded: partials/data/category.tpl
4/4 09:38 [6708] - [33mwarn[39m: [meta/templates] Partial not loaded: partials/variables/reset_code.tpl
4/4 09:38 [6708] - [33mwarn[39m: [meta/templates] Partial not loaded: partials/data/category.tpl
4/4 09:38 [6708] - [33mwarn[39m: [meta/templates] Partial not loaded: partials/variables/tag.tpl
4/4 09:38 [6708] - [33mwarn[39m: [meta/templates] Partial not loaded: partials/data/topic.tpl
4/4 09:38 [6708] - [33mwarn[39m: [meta/templates] Partial not loaded: partials/variables/topic.tpl
4/4 09:38 [6708] - [33mwarn[39m: [meta/templates] Partial not loaded: partials/data/category.tpl
4/4 09:38 [6708] - [33mwarn[39m: [meta/templates] Partial not loaded: partials/data/category.tpl
4/4 09:38 [6708] - [33mwarn[39m: [meta/templates] Partial not loaded: partials/variables/category.tpl
4/4 09:38 [6708] - [33mwarn[39m: [meta/templates] Partial not loaded: partials/variables/account.tpl
4/4 09:38 [6708] - [33mwarn[39m: [meta/templates] Partial not loaded: partials/variables/account/edit.tpl
4/4 09:38 [6708] - [33mwarn[39m: [meta/templates] Partial not loaded: partials/variables/account.tpl
4/4 09:38 [6708] - [33mwarn[39m: [meta/templates] Partial not loaded: partials/variables/account.tpl
4/4 09:38 [6708] - [33mwarn[39m: [meta/templates] Partial not loaded: partials/variables/account.tpl
4/4 09:38 [6708] - [33mwarn[39m: [meta/templates] Partial not loaded: partials/variables/account/profile.tpl
4/4 09:38 [6708] - [33mwarn[39m: [meta/templates] Partial not loaded: partials/variables/account.tpl
4/4 09:38 [6708] - [33mwarn[39m: [meta/templates] Partial not loaded: partials/data/category.tpl
4/4 09:38 [6708] - [33mwarn[39m: [meta/templates] Partial not loaded: partials/variables/account.tpl
4/4 09:38 [6708] - [33mwarn[39m: [meta/templates] Partial not loaded: partials/data/category.tpl
4/4 09:38 [6708] - [33mwarn[39m: [meta/templates] Partial not loaded: partials/variables/account.tpl
4/4 09:38 [6708] - [33mwarn[39m: [meta/templates] Partial not loaded: partials/variables/groups/details.tpl
4/4 09:38 [6708] - [33mwarn[39m: [meta/templates] Partial not loaded: partials/data/category.tpl

Does anyone of you have any ideas?

Best,
Sebastian

**Comment by deckardstp** [comment]
Is it depending on my running version? 0.61? I've read that it'll be the new standard theme in 0.7?

**Comment by pichalite** [comment]
@deckardstp The theme only works with NodeBB v0.7.0

**Comment by deckardstp** [comment]
Thanks for your fast reply!
