### ISSUE TITLE
add widget areas to profile.tpl

### ISSUE THREAD

**Issue by barisusakli** [NodeBB/nodebb-theme-persona#475]

**Comment by chocolate012** [comment]
It should basically be possible to add widgets to any .tpl E.g. users.

**Comment by julianlam** [comment]
@barisusakli There's an idea... technically, `header`, `footer`, and `sidebar` widgets need not depend on a hardcoded widget area in the template, so these could be added to all templates... :thinking:

**Comment by fais3000** [comment]
@julianlam If that does happen in addition to having a sane (easy) way to backup widgets. I believe it would make nodebb the most flexible forum software for customizations. Because it makes it so easy for non techies to show their creativity on different dynamic templates.

**Comment by barisusakli** [comment]
This adds a header widget area to all profile pages. https://github.com/NodeBB/nodebb-theme-persona/commit/37a1709fe79eb5a709b2a5865ed82ebaf7737f7e
