### ISSUE TITLE
Move partials/topic/browsing-users.tpl to nodebb-plugin-browsing-users

### ISSUE THREAD

**Issue by julianlam** [NodeBB/nodebb-theme-persona#476]
Seems like it was left over and not used anywhere, but should be in the plugin instead of the theme.

**Comment by julianlam** [comment]
When moved over, it would then be best parsed client-side on topic.tpl and injected into the DOM. Potentially not ideal but could be better than having the partial floating in core.. :thinking:

**Comment by pitaj** [comment]
Make a widget area where the partial would have been.
