### ISSUE TITLE
can't get the latest update from this repo

### ISSUE THREAD

**Issue by Zerefdev** [NodeBB/nodebb-theme-persona#488]
`[outdated] nodebb-theme-persona installed v10.1.16, package.json requires 9.1.36`
after upgrading, nodebb reverts the theme back to 9.1.36.
Also the URL in package.json should be changed

**Comment by Zerefdev** [comment]
![lll](https://user-images.githubusercontent.com/25670700/63508869-1fafaf00-c4db-11e9-947d-a893b4816be2.PNG)

**Comment by Zerefdev** [comment]
![lllllllllll](https://user-images.githubusercontent.com/25670700/63512051-17f40880-c4e3-11e9-977e-feddd766caf5.PNG)

**Comment by julianlam** [comment]
This is intentional because the latest persona requires the latest version of NodeBB which has not been released yet.

If you're running latest master, just run `./nodebb upgrade -mi`
