### ISSUE TITLE
Double-up-arrow link

### ISSUE THREAD

**Issue by nhlpl** [NodeBB/nodebb-theme-persona#49]
It was an interesting read about a possible bug.
https://community.nodebb.org/topic/4175/infinite-request-loop-wrong-post-count

And I found something similar can be reproduced on your Community Forums.

Steps to reproduce:

1. Open a thread with some replies and pagination enabled with 2 pages.
https://community.nodebb.org/topic/4159/wrong-message-shown-for-invalid-username-and-password
or
https://community.nodebb.org/topic/72/we-need-your-help

2. You'll see "3 out of 25" on the top of the page near to Search and it should be "1 out of 25".

3. Scroll down to get let say "12 out of 25" on the posts counter.

4. Use double-up-arrow link and you'll see "4 out of 25" instead of "1 out of 25".
https://community.nodebb.org/topic/72/we-need-your-help
and I can see post number 1
https://community.nodebb.org/topic/72/we-need-your-help/1

5. Use it again. Jump to "25 out of 25" and double-up-arrow will give "3 out of 25". This time I can see a topic title and."Home / Announcements / We need your help" navigation.

**Comment by MegaGM** [comment]
:+1: 
Something wrong with "pagination", definitely.

**Comment by pichalite** [comment]
Is this related to this issue?

https://github.com/NodeBB/NodeBB/issues/2878

**Comment by pitaj** [comment]
Can no longer reproduce. The wrong number is still there, but it not affected by the double up arrow. Technically, the "wrong" number isn't wrong, because it records the lowest position you can see on your screen.
