### ISSUE TITLE
Feature request: make last post text on categories view clickable

### ISSUE THREAD

**Issue by mfursov** [NodeBB/nodebb-theme-persona#495]
Hi guys,

Could you please make by default or add an option to make the text of the last post on category view clickable?

Today user see the last post but to navigate to the topic he had to click the timestamp above, which is not very intuitive.  The post author icon is very close to the timestamp and if clicked user see the profile page of the author, not the post.

I believe there will be no usability problems if the whole abbreviated text in the last post widget will become clickable. It is hard to imagine that users may want to select this text (it won't be convenient if you make the text clickable). But seeing the last post and navigating to the post page should be a very frequent scenario.

**Comment by dbell-dataxu** [comment]
Seconded, this should really be a widget.

**Comment by mfursov** [comment]
Thank you!
