### ISSUE TITLE
No line breaks in quickreply

### ISSUE THREAD

**Issue by magnusvhendin** [NodeBB/nodebb-theme-persona#497]
- **NodeBB version:** 1.13.2
- **NodeBB git hash:** 71f4607db4e2252995d488b1968f7e9bb1d97efc

- **Installed NodeBB Plugins:** 
	* nodebb-plugin-composer-default (installed, disabled)
	* nodebb-plugin-composer-quill (installed, disabled)
	* nodebb-plugin-composer-redactor (installed, enabled)
	* nodebb-plugin-dbsearch (installed, enabled)
	* nodebb-plugin-emailer-sendgrid (installed, enabled)
	* nodebb-plugin-emoji (installed, enabled)
	* nodebb-plugin-emoji-android (installed, enabled)
	* nodebb-plugin-markdown (installed, disabled)
	* nodebb-plugin-mentions (installed, enabled)
	* nodebb-plugin-ns-custom-fields (installed, enabled)
	* nodebb-plugin-soundpack-default (installed, enabled)
	* nodebb-plugin-spam-be-gone (installed, disabled)
	* nodebb-rewards-essentials (installed, enabled)
	* nodebb-theme-persona (installed, disabled)
	* nodebb-widget-essentials (installed, enabled)

- **Database type:** mongo

- **Database version:** 4.2.3

- **Exact steps to cause this issue:**
1. Enable quickreply.
2. Respond to a post using several lines.
3. Send reply.
- **What you expected:**
I expected the reply that appends to the bottom to contain those new lines.
- **What happened instead:**
The message gets slapped together into a string containing no new lines. Refreshing the page does nothing, but if you manually open the reply for edit, the line breaks are there. Saving fixes it.

**Comment by julianlam** [comment]
[sarcasm]
... maybe we should override the enter key to do nothing instead of inserting a line break in the quick reply box :laughing: 
[/sarcasm]

Thanks for reporting!

**Comment by julianlam** [comment]
Ah, it looks like this is actually a bug with Redactor, which isn't supported anymore. The functionality actually works fine with the default composer + markdown.
