### ISSUE TITLE
Improving Accessibility

### ISSUE THREAD

**Issue by jedimonkey** [NodeBB/nodebb-theme-persona#502]
We have made a theme that extends persona, and now I've been tasked with improving the accessibility, which I'm doing in a fork of this theme and planning on submitting a PR. However how do I handle adding words to the language system as I need to add phrases/labels.

**Comment by psychobunny** [comment]
Hi @jedimonkey so you can find our language strings in the core code here:
https://github.com/NodeBB/NodeBB/tree/master/public/language/en-GB

And then you can utilize this syntax for example:
https://github.com/NodeBB/nodebb-theme-persona/blob/master/templates/confirm.tpl#L3
which correlates to the string in this file:
https://github.com/NodeBB/NodeBB/blob/master/public/language/en-GB/notifications.json#L50

Hope that makes sense. Once you commit to en-GB, it will be pushed to our transifex project where people can help to translate to other languages:
http://transifex.com/nodebb

Thank you :)

**Comment by julianlam** [comment]
Please keep in mind we wouldn't want translation strings in core that are Persona-specific, so the feature or label itself should also be ported to our other themes.

If it is a Persona-specific label, then there are facilities to let you maintain the translation here (check the `languages/` directory)
