### ISSUE TITLE
Rejected flags don't have label on them

### ISSUE THREAD

**Issue by mohammadhassan99** [NodeBB/nodebb-theme-persona#513]
NodeBB version: 1.16.1

![image](https://user-images.githubusercontent.com/31972226/104049857-e1fc1500-51fa-11eb-9ced-7bc2fa9575b9.png)

**Comment by julianlam** [comment]
@mohammadhassan99 What language is that? The rejected labels are appearing for me.

**Comment by mohammadhassan99** [comment]
@julianlam I tested on both en-US and fa-IR

**Comment by pitaj** [comment]
Can you try en-GB?

**Comment by mohammadhassan99** [comment]
@pitaj Yeah. Just tested, no difference

**Comment by julianlam** [comment]
@mohammadhassan99 In one of the rejected flags, there should be a flagId (you can see it in the URL when you enter the flag details page).

Can you get me the output of `hgetall flag:<flagId>`? In mongodb it is `db.objects.find({ _key: "flag:<flagId>" }).pretty();`

replace `<flagId>` with the number, as appropriate.

**Comment by mohammadhassan99** [comment]
After rebuilding NodeBB, it now works without problem.

Thanks @julianlam @pitaj 😃
