### ISSUE TITLE
Carousel Indicator Broken on Mobile

### ISSUE THREAD

**Issue by sm2x** [NodeBB/nodebb-theme-persona#514]
NodeBB v1.16.1
nodebb-plugin-recent-cards v2.0.13 (psychobunny's)
nodebb-plugin-theme-persona v10.3.19

Recent card carousel indicator is not showing properly on Mobile devices as opposed to desktops.

![image](https://user-images.githubusercontent.com/6595333/104950840-62d9be80-59fc-11eb-87a7-7092e0d40947.png)

**Comment by julianlam** [comment]
nodebb-plugin-recent-cards#27

We'll move those into the main issue tracker as well...
