### ISSUE TITLE
Guests gravatar

### ISSUE THREAD

**Issue by nhlpl** [NodeBB/nodebb-theme-persona#53]
A local image should replace Guests gravatar for faster Users page load.
https://community.nodebb.org/users

```
<li class="users-box anon-user">
			<img src="https://secure.gravatar.com/avatar/">
			<br>
			<div class="user-info">
				<span id="online_anon_count">59</span>
				<span>Guests</span>
			</div>
		</li>
```

**Comment by psychobunny** [comment]
Technically speaking, after loading that avatar the first time, the rest of them should be cached (so performance wise it shouldn't be even noticeable - one load for multiple users)

Also, core has several choices for gravatar defaults: 

![](http://i.imgur.com/111UCGM.png)

So I would say that this issue isn't theme specific, I will close this, but feel free to suggest something on core tracker
