### ISSUE TITLE
Typo? - flaggged

### ISSUE THREAD

**Issue by uplift** [NodeBB/nodebb-theme-persona#530]
https://github.com/NodeBB/nodebb-theme-persona/blob/91c930cbac2390aeb686667632258228d5d301d7/templates/partials/topic/post-menu-list.tpl#L102

**Comment by barisusakli** [comment]
https://github.com/NodeBB/nodebb-theme-persona/issues/529 😆

**Comment by uplift** [comment]
@barisusakli 😆 I knew I'd reported it before. Someone reported it to me this morning and had sense of deja vu but my quick search was obviously not thorough enough. Apologies, Ill look harder next time 🤦‍♂️

**Comment by barisusakli** [comment]
No worries 👍🏼
