### ISSUE TITLE
Admin Plugin Page Not Found

### ISSUE THREAD

**Issue by ylothar** [NodeBB/nodebb-theme-persona#531]
Upgraded from v18.0 to v18.2, menu admin page "admin/plugins/persona" not working anymore with message:

" /talk/api/admin/plugins/persona Not Found
You seem to have stumbled upon a page that does not exist. Return to the home page."

My NodeBB setup has got a "XXXX.it/talk" root path.

![nodebb](https://user-images.githubusercontent.com/682247/132951666-4ea46380-03db-49aa-a32a-a67f820535ae.jpg)

**Comment by julianlam** [comment]
Hey there, have you run `./nodebb build` and try again?

**Comment by ylothar** [comment]
I've done it twice and with no improvement :stuck_out_tongue_closed_eyes:

**Comment by barisusakli** [comment]
Fixed in 11.2.6, thanks for reporting
