### ISSUE TITLE
remove outlines

### ISSUE THREAD

**Issue by Yehonatan-Albert** [NodeBB/nodebb-theme-persona#535]
Would be nice to add this css
```
* {
    outline: none !important;
}
```

**Comment by pitaj** [comment]
Please give an example of what this would do and why

**Comment by Yehonatan-Albert** [comment]
example (pay attention to the outline in search icon)
![image](https://user-images.githubusercontent.com/83726826/142737061-8f92e678-a204-4bb4-b1d0-cef32cc541cd.png)

**Comment by julianlam** [comment]
Right, but why remove outlines from the entire site? That seems like overreach

**Comment by Yehonatan-Albert** [comment]
I recommend remove the all outlines and if necessary add a border.
Usually the outline is not useful

**Comment by julianlam** [comment]
Outlines are necessary from an accessibiliy standpoint, so unfortunately we cannot remove them for aesthetic reasons.

**Comment by Yehonatan-Albert** [comment]
> Outlines are necessary from an accessibiliy standpoint, so unfortunately we cannot remove them for aesthetic reasons.

OK
