### ISSUE TITLE
Tag classes can interfere with other CSS classes it if contain spaces

### ISSUE THREAD

**Issue by gwynnarth** [NodeBB/nodebb-theme-persona#539]
Hello,

In https://github.com/NodeBB/nodebb-theme-persona/commit/51cd52bcc4029ea8332398f773ca457d67040e88 a functionality that renders an additional `tag-[TAG NAME]` inside class attribute has been added. Unfortunately this does not handle situations where tag consists of multiple, whitespace separated words.

For example if someone added a tag `Google Account` then this would get rendered as `<span class="tag tag-item tag-google account" ...>`. Now, if `account` happens to be a valid CSS class then this HTML element will most likely be incorrectly styled by adopting styling for that class.

Solution would be, for example, to convert all whitespaces in tag name to `-` or `_` prior to rendering it as a class name in the `span` element.

**Comment by barisusakli** [comment]
Thanks for reporting @gwynnarth this has been fixed in https://github.com/NodeBB/NodeBB/issues/10052.
And the class name is changed to `tag-class-<tagName>`. spaces are converted to dashes as well.
