### ISSUE TITLE
Latest Users always Online

### ISSUE THREAD

**Issue by nhlpl** [NodeBB/nodebb-theme-persona#54]
How to reproduce:

1. Open https://community.nodebb.org/users/latest
2. Look for mengchlei, WhichInv, Denis Glebov, adom.coco, DaMith Harischandrathilaka, 熊绎曼, Cosmin Apreutesei 
3. Open https://community.nodebb.org/user/cosmin-apreutesei
Last Online 2 days ago

**Comment by barisusakli** [comment]
The problem comes from the fact that the green online indicator is powered by socket.io which means if the user has an open tab on nodebb it will be green. The last online time on the profile is updated when the user switches from page to page via ajaxify.

**Comment by nhlpl** [comment]
No longer an issue. Thank you for your explanation how it works.
