### ISSUE TITLE
class name error

### ISSUE THREAD

**Issue by lslzl3000** [NodeBB/nodebb-theme-persona#553]
https://github.com/NodeBB/nodebb-theme-persona/blob/498fa8ee3f2630f2d29642d0b5d9c26faf20b5f4/templates/login.tpl#L70
![Screen Shot 2022-07-28 at 05 57 13](https://user-images.githubusercontent.com/3398981/181379647-39ce2680-3e01-46fe-8313-fb0e5dcd4b97.png)

the class rendered as `col-md-6<`

**Comment by julianlam** [comment]
Nice catch! Can you edit it in GitHub? If not I can fix it later.
