### ISSUE TITLE
External images & img-responsive

### ISSUE THREAD

**Issue by nhlpl** [NodeBB/nodebb-theme-persona#56]
I have seen those two images at the time of creation and now they are wrongly displayed.
https://community.nodebb.org/topic/4054/introducing-the-nodebb-0-7-0-persona-preview/65

400 x 400 px instead of 100 x 100 px
```
<img src="http://smayly.ru/gallery/ava/Kanade/59.jpg" alt="" class="img-responsive">
```

400 x 500 px instead of 41 x 50 px
```
<img src="http://smayly.ru/gallery/anime/RedFox/6.gif" alt="" class="img-responsive">
```

**Comment by julianlam** [comment]
Yes... definitely a bug. Persona seems to add a `width: 85%` to `.img-responsive`, which isn't right.

**Comment by psychobunny** [comment]
I'm waiting for the markdown fix

**Comment by psychobunny** [comment]
It actually adds 85% width to `img` not `.img-responsive`

I'll explain the reasoning really quick: 

We add img-responsive after the fact (post load) so if you have a 4000px wide image, it will load as 4000px, which breaks the layout, and only after that will it be resized to fit the window.

So if markdown adds a special class to the image (or even just `img-responsive`), then I can change that selector for it to target it right away from the get-go and we're good
