### ISSUE TITLE
Pagination & grey nav arrows

### ISSUE THREAD

**Issue by nhlpl** [NodeBB/nodebb-theme-persona#57]
Steps to reproduce:

1. Pagination > Paginate topics and posts instead of using infinite scroll
2. Open random topic with multiple pages
3. Try to use left arrow on the first page and right arrow on the last one
4. They are active with ?page=1 (first page) & ?page=6 (last page)

I have checked how it works on other forum engines and they are usually inactive or hidden.

**Comment by barisusakli** [comment]
Seems like a core bug, they look disabled but they are still clickable, happens on lavender as well.
