### ISSUE TITLE
Too much whitespace?

### ISSUE THREAD

**Issue by barisusakli** [NodeBB/nodebb-theme-persona#58]
Right now
![image](https://cloud.githubusercontent.com/assets/2583394/7033339/635388d8-dd47-11e4-97de-f14a9167edce.png)

What about

![image](https://cloud.githubusercontent.com/assets/2583394/7033360/805fce50-dd47-11e4-9483-bff887962977.png)

Same thing can be done on /unread too.

**Comment by julianlam** [comment]
... or possibly even merging the new topic button into the breadcrumbs?

**Comment by psychobunny** [comment]
I'd be against merging into breadcrumbs, because of theming considerations

**Comment by psychobunny** [comment]
The pull right looks good though
