### ISSUE TITLE
Category name display issue on category page

### ISSUE THREAD

**Issue by pichalite** [NodeBB/nodebb-theme-persona#60]
Click on a category on home page to go to the category page
![screen shot 2015-04-07 at 7 25 03 pm](https://cloud.githubusercontent.com/assets/10014774/7037737/2caed69c-dd5c-11e4-896a-696b5161d300.png)

Cold load the page, category name changes to "CATEGORY"

![screen shot 2015-04-07 at 7 25 20 pm](https://cloud.githubusercontent.com/assets/10014774/7037739/347d7694-dd5c-11e4-9c4b-9e3ba14acf90.png)

**Comment by julianlam** [comment]
Reported upstream: https://github.com/psychobunny/templates.js/issues/29
