### ISSUE TITLE
Mark as read dropdown

### ISSUE THREAD

**Issue by nhlpl** [NodeBB/nodebb-theme-persona#63]
Steps to reproduce:
1. https://community.nodebb.org/unread
2. Use Mark as Read in the top right corner
3. Mark as Read > Selected

How to select categories?

**Comment by psychobunny** [comment]
![](http://i.imgur.com/cZq0jtP.png) clicking on the avatar, quite similar to how gmail for mobile does it. I know this isn't totally obvious right now, need to have better messaging.

**Comment by nhlpl** [comment]
Tested it for many times as works fine. Thanks for letting me know.
