### ISSUE TITLE
Styling the "Advanced Search" page

### ISSUE THREAD

**Issue by psychobunny** [NodeBB/nodebb-theme-persona#64]
Open for any suggestions

**Comment by barisusakli** [comment]
![image](https://cloud.githubusercontent.com/assets/2583394/7078071/ef87a3be-dee3-11e4-8221-1aa7a14c7857.png)

Is what I am thinking, with less crappy CSS obviously :laughing:

**Comment by barisusakli** [comment]
Maybe preferences can go into the advanced search collapse as well.

**Comment by psychobunny** [comment]
Could the results be refactored to utilize topic_list.tpl? That'd be cool and save on unnecessary extra styling
