### ISSUE TITLE
Display # of new messages for chat

### ISSUE THREAD

**Issue by cnvo** [NodeBB/nodebb-theme-persona#66]
![screen shot 2015-04-18 at 1 50 26 pm](https://cloud.githubusercontent.com/assets/113159/7216569/d8d96a0e-e5d1-11e4-8ec6-8d95793e3a03.png)

**Comment by psychobunny** [comment]
Sexy. I think I can update this number client side as chats come in, but on cold loads I might have to do some magic, hmm
