### ISSUE TITLE
Uploaded images disappeared

### ISSUE THREAD

**Issue by seaswift** [NodeBB/nodebb-theme-persona#67]
Uploaded images that were hosted at uploads/files/filename.jpg disappeared even though the link to those images (siteurl/uploads/files/name.jpg) still work

**Comment by julianlam** [comment]
This is a core issue, possibly from some changes I made earlier to the markdown plugin. 

Please report the "url" parameter in your config.json.

**Comment by julianlam** [comment]
Reported upstream: julianlam/nodebb-plugin-markdown#35
