### ISSUE TITLE
No widget areas defined

### ISSUE THREAD

**Issue by kurt-stolle** [NodeBB/nodebb-theme-persona#69]
When I click on widgets in the NodeBB administrator panel, I can't see any possible areas for widgets in the theme.

**Comment by psychobunny** [comment]
We're planning on revamping the widgets system soon, so putting this on hold for now. You can always create your own plugin to add more widget areas if you like

**Comment by mani95lisa** [comment]
@kurt-stolle or you can make it yourself for now like mine https://github.com/mani95lisa/nodebb-theme-persona , add a theme.js to define more widget areas or write a plugin.

**Comment by julianlam** [comment]
Widget areas have been reintroduced into Persona
