### ISSUE TITLE
[RFC] Page transitions

### ISSUE THREAD

**Issue by psychobunny** [NodeBB/nodebb-theme-persona#72]
RFC, original thread: https://community.nodebb.org/topic/4083/page-loading/13

I'm also thinking about bringing back the old Lavender loading bar as well (with a bit of an upgrade of course, needs to be a bit more subtle imo)

**Comment by julianlam** [comment]
:+1:

**Comment by kurdin** [comment]
:+1:

**Comment by psychobunny** [comment]
closed in 0.1.49
