### ISSUE TITLE
Since 0.1.40 I no longer see timestamps anywhere

### ISSUE THREAD

**Issue by zetas** [NodeBB/nodebb-theme-persona#75]
Not sure what happened but I just upgraded this theme from the ACP and all the sudden all my timestamps disappeared. Is there something I'm missing?

I had to downgrade to 1.38. I'm not 100% sure exactly which version is the cutoff but 1.40 definitely caused it.

And yes, I reloaded/restarted, and deleted the public/stylesheets.css just in case and cleared cache in my browsers.

**Comment by psychobunny** [comment]
> timestamps disappeared

sounds like a JS problem. Any error log in the console?

**Comment by zetas** [comment]
Ah, let me close this. I upgraded again to the latest a week or so after this and it went away. 

There were no errors anywhere though.
