### ISSUE TITLE
Signatures

### ISSUE THREAD

**Issue by mastacontrola** [NodeBB/nodebb-theme-persona#81]
Would it be possible to add signatures back to the forum posts?  We much prefer the persona theme over vanilla or lavender.  Being a forum that tries to help others, our signatures often have links to useful resources, quick finds, etc... Having these visible and usable in posts is always helpful.

**Comment by prachaquant** [comment]
+1

**Comment by jbob182** [comment]
I would also greatly appreciate this feature.
