### ISSUE TITLE
Windows Mobile Menu Disappears

### ISSUE THREAD

**Issue by Punkbob** [NodeBB/nodebb-theme-persona#83]
I have a mobile user that runs windows phone, and he complains that the menu expands out of the side and then disappears. He's not the most technical user, so I just went ahead and used browser stack to test the issue, and I think I am getting the same issue that he does. 

![bs_winphone_mobile_nokia lumia 925-8 1-720x1280](https://cloud.githubusercontent.com/assets/2439778/7784780/d911147a-013f-11e5-8bb8-21b534885715.jpg)

That's is all that appears after pushing the menu button on a Windows Phone emulator when I try it on the nodebb community forums.

**Comment by brownsmart** [comment]
Serious, this issue has been reported since may and no response yet? At least point us in the right direction so we can help ourselves!?!

**Comment by brownsmart** [comment]
Closed? does that mean fixed?

**Comment by psychobunny** [comment]
In 0.7.4, which should be released in the next few days

**Comment by brownsmart** [comment]
Excellent!! your a don! mate, nice one!
