### ISSUE TITLE
Bootswatch messes up the new taskbar

### ISSUE THREAD

**Issue by Alpacatty** [NodeBB/nodebb-theme-persona#84]
Applying any Bootswatch skin to Persona results in something that looks like this:
![](http://i.imgur.com/cb0fM3v.png)
it's stretched like, only halfway across the screen and has a background colour when it shouldn't have any.

**Comment by mrgame64** [comment]
I can confirm I'm having the same problem.

**Comment by mrgame64** [comment]
Here's a working fix for this issue

**Comment by psychobunny** [comment]
dd2a96a975b1cd4c7aeae3e6c7b6e011d05d71de
