### ISSUE TITLE
Title bar is offset when scrolled down page and menu closed

### ISSUE THREAD

**Issue by bdharrington7** [NodeBB/nodebb-theme-persona#89]
Hard to describe, but on iPhone safari, this happens:
![image](https://cloud.githubusercontent.com/assets/4553795/7829334/920485ea-03f5-11e5-96e7-c1a9eb6087d3.jpg)

This happens when you scroll down a bit, then open and close the menu on mobile. 
The menu bar seems to move further down the further scrolled down you are too, so it's likely related to the page position

**Comment by pitaj** [comment]
Is this still happening?

**Comment by psychobunny** [comment]
Menu has been refactored since then, I can't repro on an old iPhone 4s so I'd assume it's okay for later models as well
