### ISSUE TITLE
Templates: future sections

### ISSUE THREAD

**Issue by NicolasSiver** [NodeBB/nodebb-theme-persona#92]
Why this construction does not work:

#### category-item.tpl

    
    <li component="categories/category" data-cid="{../cid}" data-numRecentReplies="1" class="row clearfix">
        <meta itemprop="name" content="{../name}">
    
        <div class="col-md-12 content">
            <h1 class="title section">
                
                <br />
                <small>{../description}</small>
            </h1>
        </div>
        
    </li>
    
    
    

#### list.tpl

    
    <ul class="subcategories">
        
        {../children.name}
        
    </ul>

**Comment by NicolasSiver** [comment]
![screen shot 2015-06-20 at 12 14 04 am](https://cloud.githubusercontent.com/assets/135263/8263221/555e1dc8-16e1-11e5-8d2b-7f080a7892b6.png)

**Comment by NicolasSiver** [comment]
My categories for testing:

![screen shot 2015-06-20 at 12 16 14 am](https://cloud.githubusercontent.com/assets/135263/8263263/9bc9481e-16e1-11e5-9c63-4794a7c3b43c.png)

**Comment by NicolasSiver** [comment]
@psychobunny how does it work - `{../name}` It's undocumented.

Does templating engine support loop in the loop?

**Comment by NicolasSiver** [comment]
Seems there is a problem with `../` references in template, I'm reusing `partials/categories/link.tpl`, and It exits inner loop.

**Comment by NicolasSiver** [comment]
There is a mistake?

	<ul class="categories" itemscope itemtype="http://www.schema.org/ItemList">
		<p>Categories</p>
	
		
		
		<li component="categories/category" data-cid="{categories.cid}" data-numRecentReplies="1" class="row clearfix">
			<meta itemprop="name" content="{categories.name}">
	
			<div class="col-md-12 content">
				<h1 class="title section">
					
					<br />
					<small>{categories.description}</small>
				</h1>
			</div>
	
			
		<span class="subcategories">
			
			{categories.children.name}
			
		</span>
			
		</li>
		
		
		
		
	</ul>

I just composed templates together, for easy read.

Result:

![screen shot 2015-07-02 at 7 36 01 pm](https://cloud.githubusercontent.com/assets/135263/8482319/9db1b034-20f1-11e5-975a-e8ce0223242a.png)

**Comment by barisusakli** [comment]
@NicolasSiver @psychobunny just fixed a bug related to ../{value}  in templates.js can you give this another just maybe its fixed now.

**Comment by NicolasSiver** [comment]
I will, thanks
